# Generated by Django 4.2.26 on 2025-11-29 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouses", "0001_initial"),
        ("fpos", "0001_initial"),
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("production", "Production Report"),
                            ("procurement", "Procurement Report"),
                            ("financial", "Financial Report"),
                            ("fpo_performance", "FPO Performance Report"),
                            ("market_analysis", "Market Analysis"),
                            ("loss_analysis", "Loss Analysis Report"),
                            ("policy_brief", "Policy Brief"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                            ("fpo", "FPO-specific"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.FileField(upload_to="reports/")),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used to generate report"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FPOComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_name", models.CharField(max_length=200)),
                ("financial_year", models.CharField(max_length=10)),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="\n        {\n            'fpo_id': {\n                'revenue': 5000000,\n                'members': 250,\n                'production': 1500,\n                'avg_member_income': 25000,\n                ...\n            }\n        }\n        ",
                    ),
                ),
                (
                    "rankings",
                    models.JSONField(
                        default=dict, help_text="Rankings for each metric"
                    ),
                ),
                ("top_performers", models.JSONField(default=list)),
                ("best_practices_identified", models.TextField(blank=True)),
                ("key_insights", models.TextField()),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpos",
                    models.ManyToManyField(related_name="comparisons", to="fpos.fpo"),
                ),
            ],
            options={
                "verbose_name": "FPO Comparison",
                "verbose_name_plural": "FPO Comparisons",
                "db_table": "fpo_comparisons",
            },
        ),
        migrations.CreateModel(
            name="ProductionStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("block", models.CharField(blank=True, max_length=100)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Area in hectares", max_digits=12
                    ),
                ),
                (
                    "total_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Production in tonnes",
                        max_digits=15,
                    ),
                ),
                (
                    "average_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yield in quintal/hectare",
                        max_digits=8,
                    ),
                ),
                ("number_of_farmers", models.IntegerField(default=0)),
                ("fpo_farmers", models.IntegerField(default=0)),
                ("non_fpo_farmers", models.IntegerField(default=0)),
                (
                    "premium_quality_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "standard_quality_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "substandard_quality_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_price_realized",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average price per quintal",
                        max_digits=10,
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total production value in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "yield_variance_from_benchmark",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage variance", max_digits=6
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("fpo", "FPO Data"),
                            ("govt", "Government Survey"),
                            ("estimated", "Estimated"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_stats",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Statistics",
                "verbose_name_plural": "Production Statistics",
                "db_table": "production_stats",
                "unique_together": {("crop", "state", "district", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="LossAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("loss_date", models.DateField()),
                ("season", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                (
                    "loss_stage",
                    models.CharField(
                        choices=[
                            ("harvesting", "During Harvesting"),
                            ("threshing", "During Threshing"),
                            ("drying", "During Drying"),
                            ("storage", "During Storage"),
                            ("transportation", "During Transportation"),
                            ("processing", "During Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "loss_cause",
                    models.CharField(
                        choices=[
                            ("spillage", "Spillage"),
                            ("moisture", "Moisture/Humidity"),
                            ("pest", "Pest Attack"),
                            ("rodents", "Rodents"),
                            ("birds", "Birds"),
                            ("fungal", "Fungal Infection"),
                            ("improper_handling", "Improper Handling"),
                            ("poor_infrastructure", "Poor Infrastructure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "loss_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loss quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "loss_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "market_price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "financial_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Financial loss in INR",
                        max_digits=15,
                    ),
                ),
                ("preventive_measures_available", models.BooleanField(default=False)),
                ("preventive_measures_description", models.TextField(blank=True)),
                ("recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_analyses",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_records",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_records",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loss Analysis",
                "verbose_name_plural": "Loss Analyses",
                "db_table": "loss_analyses",
                "indexes": [
                    models.Index(
                        fields=["loss_date"], name="loss_analys_loss_da_0c5aae_idx"
                    ),
                    models.Index(
                        fields=["loss_stage"], name="loss_analys_loss_st_9b118b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KPIMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("production", "Production Volume"),
                            ("area", "Area Under Cultivation"),
                            ("yield", "Average Yield"),
                            ("price", "Average Price"),
                            ("revenue", "Revenue"),
                            ("fpo_count", "Number of FPOs"),
                            ("farmer_count", "Number of Farmers"),
                            ("procurement", "Procurement Volume"),
                            ("loss", "Post-harvest Loss"),
                            ("value_addition", "Value Addition %"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                            ("fpo", "FPO"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField()),
                ("month", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField(blank=True, null=True)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "unit",
                    models.CharField(help_text="Unit of measurement", max_length=50),
                ),
                (
                    "previous_period_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "percentage_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "achievement_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_metrics",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Metric",
                "verbose_name_plural": "KPI Metrics",
                "db_table": "kpi_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_type", "scope"],
                        name="kpi_metrics_metric__cc7874_idx",
                    ),
                    models.Index(fields=["date"], name="kpi_metrics_date_377a02_idx"),
                    models.Index(
                        fields=["year", "quarter"], name="kpi_metrics_year_80afd0_idx"
                    ),
                ],
            },
        ),
    ]
