# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processing", "0001_initial"),
        ("crops", "0001_initial"),
        ("farmers", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FPOCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "total_quantity_procured",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "average_procurement_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "average_selling_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "gross_commission",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "operational_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_commission",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "allocated_to_reserve",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "allocated_to_operations",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "allocated_to_dividend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_records",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Commission",
                "verbose_name_plural": "FPO Commissions",
                "db_table": "fpo_commissions",
            },
        ),
        migrations.CreateModel(
            name="ProcurementOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_fulfilled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fulfilled quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "quality_grade_required",
                    models.CharField(
                        choices=[
                            ("A", "Grade A"),
                            ("B", "Grade B"),
                            ("C", "Grade C"),
                            ("any", "Any Grade"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "quality_specifications",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed quality specs: moisture %, oil content, etc.",
                    ),
                ),
                (
                    "base_price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("msp_applicable", models.BooleanField(default=True)),
                (
                    "minimum_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="MSP or minimum acceptable price",
                        max_digits=10,
                    ),
                ),
                (
                    "maximum_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("bidding_start_date", models.DateField()),
                ("bidding_end_date", models.DateField()),
                ("delivery_start_date", models.DateField()),
                ("delivery_end_date", models.DateField()),
                (
                    "collection_centers",
                    models.JSONField(
                        default=list, help_text="List of collection center locations"
                    ),
                ),
                ("payment_terms", models.TextField()),
                ("delivery_terms", models.TextField()),
                ("penalty_clause", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("bidding", "Bidding Open"),
                            ("awarded", "Awarded"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_procurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_orders",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Order",
                "verbose_name_plural": "Procurement Orders",
                "db_table": "procurement_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("collection_center", models.CharField(max_length=200)),
                ("batch_number", models.CharField(max_length=50)),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Delivered quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        decimal_places=2, help_text="Moisture %", max_digits=5
                    ),
                ),
                (
                    "oil_content",
                    models.DecimalField(
                        decimal_places=2, help_text="Oil %", max_digits=5
                    ),
                ),
                (
                    "foreign_matter",
                    models.DecimalField(
                        decimal_places=2, help_text="Foreign matter %", max_digits=5
                    ),
                ),
                (
                    "damaged_seeds",
                    models.DecimalField(
                        decimal_places=2, help_text="Damaged seeds %", max_digits=5
                    ),
                ),
                (
                    "final_grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A (Premium)"),
                            ("B", "Grade B (Standard)"),
                            ("C", "Grade C (Below Standard)"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("grade_justification", models.TextField()),
                (
                    "quantity_accepted",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Accepted quantity after grading",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_rejected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "grading_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="quality_certificates/"
                    ),
                ),
                ("farmer_acknowledged", models.BooleanField(default=False)),
                (
                    "farmer_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_gradings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procurement_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_grades",
                        to="procurement.procurementorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Grade",
                "verbose_name_plural": "Quality Grades",
                "db_table": "quality_grades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "fpo_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="FPO commission amount",
                        max_digits=10,
                    ),
                ),
                (
                    "transport_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("deduction_details", models.JSONField(default=dict)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer (NEFT/RTGS)"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("transaction_reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fpos.fpo"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procurement_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="procurement.procurementorder",
                    ),
                ),
                (
                    "quality_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="procurement.qualitygrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_supplied",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("base_payment", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "quality_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "loyalty_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "performance_bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_payment", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
                    ),
                ),
                (
                    "fpo_commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_payments",
                        to="procurement.fpocommission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Payment",
                "verbose_name_plural": "Member Payments",
                "db_table": "member_payments",
            },
        ),
        migrations.AddField(
            model_name="fpocommission",
            name="procurement_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="procurement.procurementorder",
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("season", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                (
                    "contracted_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Contracted area in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "expected_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected production in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "agreed_price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_adjustment_clause", models.TextField()),
                ("quality_specifications", models.JSONField(default=dict)),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField()),
                ("terms_and_conditions", models.TextField()),
                (
                    "fpo_obligations",
                    models.TextField(help_text="What FPO will provide"),
                ),
                (
                    "farmer_obligations",
                    models.TextField(help_text="What farmer must do"),
                ),
                ("seed_support_provided", models.BooleanField(default=False)),
                ("fertilizer_support_provided", models.BooleanField(default=False)),
                ("technical_support_provided", models.BooleanField(default=True)),
                ("credit_support_provided", models.BooleanField(default=False)),
                ("farmer_signed", models.BooleanField(default=False)),
                ("farmer_signature_date", models.DateField(blank=True, null=True)),
                ("fpo_signed", models.BooleanField(default=False)),
                ("fpo_signature_date", models.DateField(blank=True, null=True)),
                ("contract_document", models.FileField(upload_to="contracts/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("breached", "Breached"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "actual_production",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "contract_fulfillment_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_offered",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Offered quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_bid_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("quality_grade_offered", models.CharField(max_length=10)),
                (
                    "quality_certificate_url",
                    models.FileField(
                        blank=True, null=True, upload_to="bids/quality_certificates/"
                    ),
                ),
                ("proposed_delivery_date", models.DateField()),
                ("delivery_location", models.CharField(max_length=200)),
                ("payment_terms_acceptance", models.BooleanField(default=True)),
                ("special_terms", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "evaluation_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score out of 100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="processing.processingunit",
                    ),
                ),
                (
                    "procurement_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="procurement.procurementorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
                "db_table": "bids",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
