# Generated by Django 4.2.26 on 2025-12-01 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FPO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "fpo_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("contact_person", models.CharField(max_length=200)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[6-9]\\d{9}$")
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("total_members", models.IntegerField(default=0)),
                (
                    "total_land_area",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Hectares", max_digits=10
                    ),
                ),
                (
                    "monthly_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quintals/month",
                        max_digits=10,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_fpo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fpos",
            },
        ),
        migrations.CreateModel(
            name="FPOMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "land_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Hectares", max_digits=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "db_table": "fpo_memberships",
                "indexes": [
                    models.Index(
                        fields=["fpo", "is_active"],
                        name="fpo_members_fpo_id_c693d1_idx",
                    )
                ],
                "unique_together": {("fpo", "farmer")},
            },
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(fields=["fpo_code"], name="fpos_fpo_cod_e7692b_idx"),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(
                fields=["district", "state"], name="fpos_distric_3ba41a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(
                fields=["is_verified", "is_active"], name="fpos_is_veri_c59f25_idx"
            ),
        ),
    ]
