# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FPO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("fpo_id", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("producer_company", "Producer Company (Section 581C)"),
                            ("cooperative", "Cooperative Society"),
                            ("trust", "Trust"),
                            ("society", "Society"),
                        ],
                        max_length=30,
                    ),
                ),
                ("registration_number", models.CharField(max_length=50, unique=True)),
                (
                    "registration_authority",
                    models.CharField(
                        choices=[
                            ("roc", "Registrar of Companies (RoC)"),
                            ("cooperative_dept", "Cooperative Department"),
                            ("charity_commissioner", "Charity Commissioner"),
                            ("society_registrar", "Society Registrar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("registration_date", models.DateField()),
                ("incorporation_date", models.DateField()),
                ("registered_address", models.TextField()),
                ("operational_address", models.TextField(blank=True)),
                ("village", models.CharField(max_length=100)),
                ("block", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("operational_area", models.JSONField(blank=True, null=True)),
                ("contact_person_name", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=10)),
                ("contact_email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "authorized_share_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "paid_up_share_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "share_value_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("branch_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("ifsc_code", models.CharField(max_length=11)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("current", "Current Account"),
                            ("savings", "Savings Account"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("pan_number", models.CharField(max_length=10, unique=True)),
                ("tan_number", models.CharField(blank=True, max_length=10)),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                ("fssai_license", models.CharField(blank=True, max_length=14)),
                ("agmark_certification", models.BooleanField(default=False)),
                ("total_members", models.IntegerField(default=0)),
                ("male_members", models.IntegerField(default=0)),
                ("female_members", models.IntegerField(default=0)),
                ("sc_st_members", models.IntegerField(default=0)),
                (
                    "total_land_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total member land in acres",
                        max_digits=12,
                    ),
                ),
                (
                    "annual_turnover",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual turnover in INR",
                        max_digits=15,
                    ),
                ),
                ("nabard_support", models.BooleanField(default=False)),
                (
                    "nabard_grant_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("sfac_support", models.BooleanField(default=False)),
                (
                    "sfac_grant_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "health_score",
                    models.IntegerField(
                        default=0, help_text="FPO health score (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fpo_as_ceo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chairman",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fpo_as_chairman",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO",
                "verbose_name_plural": "FPOs",
                "db_table": "fpos",
            },
        ),
        migrations.CreateModel(
            name="FPOShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("issue", "Share Issued"),
                            ("transfer", "Share Transferred"),
                            ("buyback", "Share Buyback"),
                            ("forfeiture", "Share Forfeiture"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("shares_count", models.IntegerField()),
                (
                    "share_value_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("online", "Online Transfer"),
                            ("upi", "UPI"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_transactions",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transferred_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_transfers_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Share",
                "verbose_name_plural": "FPO Shares",
                "db_table": "fpo_shares",
            },
        ),
        migrations.CreateModel(
            name="FPOMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("agm", "Annual General Meeting"),
                            ("egm", "Extraordinary General Meeting"),
                            ("board", "Board Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("meeting_time", models.TimeField()),
                ("venue", models.TextField()),
                ("agenda", models.TextField()),
                ("minutes", models.TextField(blank=True)),
                ("total_attendees", models.IntegerField(default=0)),
                ("quorum_met", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Meeting",
                "verbose_name_plural": "FPO Meetings",
                "db_table": "fpo_meetings",
            },
        ),
        migrations.CreateModel(
            name="FPOProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total area under cultivation in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "total_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total production in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "average_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average yield per acre",
                        max_digits=8,
                    ),
                ),
                ("participating_members", models.IntegerField()),
                (
                    "average_quality_grade",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_records",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Production",
                "verbose_name_plural": "FPO Production",
                "db_table": "fpo_production",
                "unique_together": {("fpo", "crop", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="FPOPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g., 2023-24", max_length=10),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Q1 (Apr-Jun)"),
                            (2, "Q2 (Jul-Sep)"),
                            (3, "Q3 (Oct-Dec)"),
                            (4, "Q4 (Jan-Mar)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "dividend_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_procurement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total procurement in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total sales in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "average_price_realization",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average price per quintal",
                        max_digits=10,
                    ),
                ),
                ("members_benefited", models.IntegerField(default=0)),
                (
                    "average_member_earning",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_premium_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Premium over market price (%)",
                        max_digits=5,
                    ),
                ),
                ("processing_done", models.BooleanField(default=False)),
                (
                    "value_added_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Performance",
                "verbose_name_plural": "FPO Performance",
                "db_table": "fpo_performance",
                "unique_together": {("fpo", "financial_year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="FPOGovernance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chairman", "Chairman"),
                            ("vice_chairman", "Vice Chairman"),
                            ("director", "Board Director"),
                            ("ceo", "Chief Executive Officer"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("term_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "monthly_remuneration",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly remuneration in INR",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_members",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Governance",
                "verbose_name_plural": "FPO Governance",
                "db_table": "fpo_governance",
                "unique_together": {("fpo", "member", "position")},
            },
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(fields=["fpo_id"], name="fpos_fpo_id_e27d0f_idx"),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(
                fields=["district", "state"], name="fpos_distric_3ba41a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpo",
            index=models.Index(fields=["is_active"], name="fpos_is_acti_ed5e73_idx"),
        ),
    ]
