# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fpomembership',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_memberships', to='farmers.farmerprofile'),
        ),
        migrations.AddField(
            model_name='fpomembership',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fpos.fpoprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='fpomembership',
            unique_together={('farmer', 'fpo')},
        ),
    ]
