# Generated by Django 4.2.23 on 2025-12-07 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fpos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPOJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, help_text='Message from farmer to FPO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_join_requests', to='farmers.farmerprofile')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='fpos.fpoprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FPO Join Request',
                'verbose_name_plural': 'FPO Join Requests',
                'db_table': 'fpo_join_requests',
                'ordering': ['-requested_at'],
                'unique_together': {('farmer', 'fpo', 'status')},
            },
        ),
    ]
