# Generated by Django 4.2.26 on 2025-11-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("advisories", "__first__"),
        ("fpos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("farm", "Individual Farm"),
                            ("fpo", "FPO Collective"),
                            ("state", "State Level"),
                            ("national", "National Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "total_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total production in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "marketable_surplus",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marketable surplus after self-consumption",
                        max_digits=12,
                    ),
                ),
                (
                    "already_sold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity already sold",
                        max_digits=12,
                    ),
                ),
                (
                    "available_for_sale",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Currently available for sale",
                        max_digits=12,
                    ),
                ),
                (
                    "grade_a_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "grade_b_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "grade_c_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "stored_at_farm",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stored_at_warehouse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stored_at_fpo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                ("expected_market_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_aggregates",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fpos.fpo",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Aggregate",
                "verbose_name_plural": "Supply Aggregates",
                "db_table": "supply_aggregates",
                "indexes": [
                    models.Index(
                        fields=["season", "year"], name="supply_aggr_season_508ffa_idx"
                    ),
                    models.Index(
                        fields=["state", "district"],
                        name="supply_aggr_state_4a10fd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PricePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mandi_name", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("prediction_date", models.DateField(db_index=True)),
                ("prediction_for_date", models.DateField()),
                (
                    "prediction_horizon",
                    models.CharField(
                        choices=[
                            ("1_week", "1 Week"),
                            ("2_weeks", "2 Weeks"),
                            ("1_month", "1 Month"),
                            ("3_months", "3 Months"),
                            ("6_months", "6 Months"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "predicted_min_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "predicted_max_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "predicted_modal_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=95.0,
                        help_text="Confidence level %",
                        max_digits=5,
                    ),
                ),
                ("lower_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                ("upper_bound", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("arima", "ARIMA"),
                            ("lstm", "LSTM"),
                            ("random_forest", "Random Forest"),
                            ("gradient_boosting", "Gradient Boosting"),
                            ("ensemble", "Ensemble Method"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "features_used",
                    models.JSONField(
                        default=dict, help_text="Features used for prediction"
                    ),
                ),
                (
                    "actual_modal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prediction_error",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prediction_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upward", "Price Rising"),
                            ("downward", "Price Falling"),
                            ("stable", "Price Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "volatility_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_predictions",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advisories.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Prediction",
                "verbose_name_plural": "Price Predictions",
                "db_table": "price_predictions",
                "indexes": [
                    models.Index(
                        fields=["prediction_date"],
                        name="price_predi_predict_861ab7_idx",
                    ),
                    models.Index(
                        fields=["prediction_for_date"],
                        name="price_predi_predict_1a6cfa_idx",
                    ),
                    models.Index(
                        fields=["mandi_name", "district"],
                        name="price_predi_mandi_n_365255_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("price", "Price Trend"),
                            ("demand", "Demand Trend"),
                            ("supply", "Supply Trend"),
                            ("import", "Import Trend"),
                            ("export", "Export Trend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("regional", "Regional"),
                            ("state", "State-wise"),
                            ("district", "District-wise"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("trend_description", models.TextField()),
                (
                    "key_insights",
                    models.JSONField(default=list, help_text="List of key insights"),
                ),
                (
                    "percentage_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage change over period",
                        max_digits=6,
                    ),
                ),
                (
                    "absolute_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Absolute change in value",
                        max_digits=12,
                    ),
                ),
                (
                    "year_over_year_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "influencing_factors",
                    models.JSONField(
                        default=list, help_text="Factors influencing the trend"
                    ),
                ),
                ("future_outlook", models.TextField(blank=True)),
                (
                    "chart_data",
                    models.JSONField(
                        default=dict, help_text="Data for chart rendering"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_trends",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Trend",
                "verbose_name_plural": "Market Trends",
                "db_table": "market_trends",
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="market_tren_start_d_065c1e_idx",
                    ),
                    models.Index(
                        fields=["trend_type"], name="market_tren_trend_t_981959_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FPOSupplyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "planned_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned production from all members",
                        max_digits=12,
                    ),
                ),
                (
                    "committed_to_buyers",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity already committed to buyers",
                        max_digits=12,
                    ),
                ),
                (
                    "available_for_sale",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Available for fresh commitments",
                        max_digits=12,
                    ),
                ),
                (
                    "target_quality_grade",
                    models.CharField(
                        choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                        max_length=10,
                    ),
                ),
                (
                    "minimum_acceptable_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum price per quintal",
                        max_digits=10,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target price per quintal",
                        max_digits=10,
                    ),
                ),
                ("expected_harvest_start", models.DateField()),
                ("expected_harvest_end", models.DateField()),
                ("ready_for_sale_date", models.DateField()),
                ("participating_members", models.IntegerField()),
                (
                    "total_area_committed",
                    models.DecimalField(
                        decimal_places=2, help_text="Total area in acres", max_digits=10
                    ),
                ),
                (
                    "plan_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "actual_production",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_average_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_plans",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Supply Plan",
                "verbose_name_plural": "FPO Supply Plans",
                "db_table": "fpo_supply_plans",
                "unique_together": {("fpo", "crop", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forecast_year", models.IntegerField()),
                (
                    "forecast_quarter",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Q1 (Apr-Jun)"),
                            (2, "Q2 (Jul-Sep)"),
                            (3, "Q3 (Oct-Dec)"),
                            (4, "Q4 (Jan-Mar)"),
                        ],
                        null=True,
                    ),
                ),
                ("forecast_month", models.IntegerField(blank=True, null=True)),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("domestic", "Domestic Demand"),
                            ("industrial", "Industrial Demand"),
                            ("export", "Export Demand"),
                            ("total", "Total Demand"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forecasted_demand",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Forecasted demand in tonnes",
                        max_digits=12,
                    ),
                ),
                (
                    "confidence_interval_lower",
                    models.DecimalField(
                        decimal_places=2, help_text="Lower bound", max_digits=12
                    ),
                ),
                (
                    "confidence_interval_upper",
                    models.DecimalField(
                        decimal_places=2, help_text="Upper bound", max_digits=12
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("north", "North India"),
                            ("south", "South India"),
                            ("east", "East India"),
                            ("west", "West India"),
                            ("central", "Central India"),
                            ("northeast", "North-East India"),
                            ("national", "National"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                (
                    "model_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_demand",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual demand (filled later)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "forecast_error_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "factors_considered",
                    models.JSONField(
                        default=dict,
                        help_text="{'population_growth': 1.2, 'gdp_growth': 6.5, ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "model_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="advisories.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Forecast",
                "verbose_name_plural": "Demand Forecasts",
                "db_table": "demand_forecasts",
                "indexes": [
                    models.Index(
                        fields=["forecast_year", "forecast_quarter"],
                        name="demand_fore_forecas_8f3a43_idx",
                    ),
                    models.Index(
                        fields=["region"], name="demand_fore_region_d67c79_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "crop",
                        "forecast_year",
                        "forecast_quarter",
                        "forecast_type",
                        "region",
                    )
                },
            },
        ),
    ]
