# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("processing", "0001_initial"),
        ("crops", "0001_initial"),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "listing_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Available quantity", max_digits=12
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("quintal", "Quintal"),
                            ("kg", "Kilogram"),
                            ("liter", "Liter"),
                            ("tonne", "Tonne"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_order_quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("quality_grade", models.CharField(blank=True, max_length=10)),
                (
                    "quality_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="listings/certificates/"
                    ),
                ),
                ("pickup_location", models.CharField(max_length=200)),
                ("delivery_available", models.BooleanField(default=True)),
                ("delivery_radius_km", models.IntegerField(default=0)),
                ("listing_start_date", models.DateField()),
                ("listing_end_date", models.DateField()),
                (
                    "images",
                    models.JSONField(default=list, help_text="List of image URLs"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("out_of_stock", "Out of Stock"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("inquiry_count", models.IntegerField(default=0)),
                ("order_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_listings",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Listing",
                "verbose_name_plural": "Marketplace Listings",
                "db_table": "marketplace_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("marketplace_name", models.CharField(max_length=200)),
                (
                    "marketplace_type",
                    models.CharField(
                        choices=[
                            ("fpo_platform", "FPO Platform"),
                            ("b2b", "B2B Platform"),
                            ("b2c", "B2C Platform"),
                            ("government", "Government Procurement"),
                            ("export", "Export Market"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform_url", models.URLField(blank=True)),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_listings", models.IntegerField(default=0)),
                ("total_transactions", models.IntegerField(default=0)),
                (
                    "total_gmv",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Gross Merchandise Value in INR",
                        max_digits=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace",
                "verbose_name_plural": "Marketplaces",
                "db_table": "marketplaces",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                ("buyer_contact", models.CharField(max_length=10)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_organization", models.CharField(blank=True, max_length=200)),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "delivery_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "taxes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("delivery_address", models.TextField()),
                ("delivery_pincode", models.CharField(max_length=6)),
                ("delivery_city", models.CharField(max_length=100)),
                ("delivery_state", models.CharField(max_length=100)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("expected_delivery_date", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("online", "Online Payment"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_terms", "Credit Terms"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_completed", "Payment Completed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buyer", "Buyer"),
                            ("seller", "Seller"),
                            ("platform", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="marketplace.marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace Order",
                "verbose_name_plural": "Marketplace Orders",
                "db_table": "marketplace_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_quality_rating", models.IntegerField()),
                ("delivery_rating", models.IntegerField()),
                ("packaging_rating", models.IntegerField()),
                ("overall_rating", models.IntegerField()),
                ("review_title", models.CharField(max_length=200)),
                ("review_text", models.TextField()),
                ("reviewer_name", models.CharField(max_length=200)),
                ("is_verified_buyer", models.BooleanField(default=True)),
                ("review_photos", models.JSONField(default=list)),
                ("helpful_count", models.IntegerField(default=0)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "marketplace_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="marketplace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="marketplace.marketplace",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="processing_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_listings",
                to="processing.processingunit",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processing.product",
            ),
        ),
        migrations.CreateModel(
            name="FPOMarketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("active_listings", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                ("successful_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                (
                    "gross_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "platform_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "customer_satisfaction_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_performance",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.marketplace",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Marketplace Performance",
                "verbose_name_plural": "FPO Marketplace Performance",
                "db_table": "fpo_marketplace_performance",
            },
        ),
        migrations.CreateModel(
            name="BuyerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                ("buyer_contact", models.CharField(max_length=10)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_organization", models.CharField(blank=True, max_length=200)),
                ("inquiry_text", models.TextField()),
                (
                    "quantity_required",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("response_text", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("responded", "Responded"),
                            ("converted", "Converted to Order"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_inquiry",
                        to="marketplace.order",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="marketplace.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyer Inquiry",
                "verbose_name_plural": "Buyer Inquiries",
                "db_table": "buyer_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["listing_number"], name="marketplace_listing_cf3da8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="marketplace_status_205303_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fpomarketplace",
            unique_together={("fpo", "marketplace", "month", "year")},
        ),
    ]
