# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='listing',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='lots.procurementlot'),
        ),
    ]
