# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(help_text='Company/Business name', max_length=200)),
                ('gst_number', models.CharField(blank=True, help_text='GST registration number', max_length=15)),
                ('transport_license', models.CharField(blank=True, help_text='Transport license number', max_length=50)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified status')),
                ('verification_documents', models.JSONField(blank=True, default=dict, help_text='Uploaded verification documents')),
                ('service_states', models.JSONField(blank=True, default=list, help_text='States where service is available')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5)),
            ],
            options={
                'verbose_name': 'Logistics Partner',
                'verbose_name_plural': 'Logistics Partners',
                'db_table': 'logistics_partners',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('mini_truck', 'Mini Truck (< 1 Ton)'), ('small_truck', 'Small Truck (1-3 Tons)'), ('medium_truck', 'Medium Truck (3-7 Tons)'), ('large_truck', 'Large Truck (7-15 Tons)'), ('trailer', 'Trailer (> 15 Tons)'), ('tempo', 'Tempo')], max_length=50)),
                ('capacity_quintals', models.DecimalField(decimal_places=2, help_text='Cargo capacity in quintals', max_digits=8)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('rc_document', models.FileField(blank=True, help_text='Registration Certificate', null=True, upload_to='vehicles/rc/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicles/insurance/')),
                ('pollution_certificate', models.FileField(blank=True, null=True, upload_to='vehicles/pollution/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for booking')),
                ('logistics_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.logisticspartner')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted by Logistics'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('scheduled_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('current_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted freight charges', max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('pod_image', models.ImageField(blank=True, help_text='Proof of Delivery', null=True, upload_to='shipments/pod/')),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='shipments/signatures/')),
                ('logistics_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.logisticspartner')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
