# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("procurement", "0001_initial"),
        ("marketplace", "__first__"),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("route_name", models.CharField(max_length=200)),
                ("route_code", models.CharField(max_length=20, unique=True)),
                ("origin", models.CharField(max_length=200)),
                ("origin_latitude", models.FloatField(blank=True, null=True)),
                ("origin_longitude", models.FloatField(blank=True, null=True)),
                ("destination", models.CharField(max_length=200)),
                ("destination_latitude", models.FloatField(blank=True, null=True)),
                ("destination_longitude", models.FloatField(blank=True, null=True)),
                ("route_path", models.JSONField(blank=True, null=True)),
                (
                    "waypoints",
                    models.JSONField(
                        default=list,
                        help_text="List of intermediate stops with coordinates",
                    ),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("highway", "Highway"),
                            ("state_highway", "State Highway"),
                            ("district_road", "District Road"),
                            ("village_road", "Village Road"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "road_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("average", "Average"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "total_toll_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "estimated_fuel_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "optimization_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Route efficiency score (0-100)",
                        max_digits=5,
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "average_actual_duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shipment_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity in quintals",
                        max_digits=12,
                    ),
                ),
                ("number_of_bags", models.IntegerField()),
                ("origin_location", models.CharField(max_length=200)),
                ("origin_coordinates_lat", models.FloatField(blank=True, null=True)),
                ("origin_coordinates_lng", models.FloatField(blank=True, null=True)),
                ("destination_location", models.CharField(max_length=200)),
                (
                    "destination_coordinates_lat",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "destination_coordinates_lng",
                    models.FloatField(blank=True, null=True),
                ),
                ("driver_name", models.CharField(max_length=200)),
                ("driver_contact", models.CharField(max_length=10)),
                ("scheduled_pickup_date", models.DateTimeField()),
                ("actual_pickup_date", models.DateTimeField(blank=True, null=True)),
                ("scheduled_delivery_date", models.DateTimeField()),
                ("actual_delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("vehicle_assigned", "Vehicle Assigned"),
                            ("loading", "Loading"),
                            ("in_transit", "In Transit"),
                            ("reached_destination", "Reached Destination"),
                            ("unloading", "Unloading"),
                            ("completed", "Completed"),
                            ("delayed", "Delayed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("current_latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("last_tracking_update", models.DateTimeField(blank=True, null=True)),
                (
                    "tracking_history",
                    models.JSONField(
                        default=list,
                        help_text="List of location updates with timestamps",
                    ),
                ),
                (
                    "planned_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "actual_distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "transport_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "loading_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "unloading_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "other_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("loading_quality_check", models.BooleanField(default=False)),
                ("loading_condition", models.TextField(blank=True)),
                ("unloading_quality_check", models.BooleanField(default=False)),
                ("unloading_condition", models.TextField(blank=True)),
                ("damage_reported", models.BooleanField(default=False)),
                ("damage_details", models.TextField(blank=True)),
                (
                    "lr_number",
                    models.CharField(
                        blank=True, help_text="Lorry Receipt Number", max_length=50
                    ),
                ),
                ("e_way_bill_number", models.CharField(blank=True, max_length=20)),
                (
                    "delivery_challan",
                    models.FileField(
                        blank=True, null=True, upload_to="shipments/challans/"
                    ),
                ),
                ("is_delayed", models.BooleanField(default=False)),
                ("delay_reason", models.TextField(blank=True)),
                ("delay_hours", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "marketplace_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_ref",
                        to="marketplace.order",
                    ),
                ),
                (
                    "procurement_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="procurement.procurementorder",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "db_table": "shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("truck", "Truck"),
                            ("mini_truck", "Mini Truck"),
                            ("tractor_trolley", "Tractor Trolley"),
                            ("tempo", "Tempo"),
                            ("van", "Van"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("fpo_owned", "FPO Owned"),
                            ("hired", "Hired"),
                            ("member_owned", "Member Owned"),
                            ("contracted", "Contracted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_contact", models.CharField(blank=True, max_length=10)),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="Capacity in quintals", max_digits=8
                    ),
                ),
                ("make_model", models.CharField(max_length=100)),
                ("year_of_manufacture", models.IntegerField()),
                ("registration_date", models.DateField()),
                ("registration_expiry", models.DateField()),
                ("insurance_number", models.CharField(max_length=50)),
                ("insurance_expiry", models.DateField()),
                ("fitness_certificate_expiry", models.DateField()),
                ("pollution_certificate_expiry", models.DateField()),
                ("driver_name", models.CharField(max_length=200)),
                ("driver_license_number", models.CharField(max_length=20)),
                ("driver_contact", models.CharField(max_length=10)),
                ("gps_device_id", models.CharField(blank=True, max_length=50)),
                ("gps_enabled", models.BooleanField(default=False)),
                ("current_latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("total_trips", models.IntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_vehicle",
                        to="logistics.shipment",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
            },
        ),
        migrations.CreateModel(
            name="TransportBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_number", models.CharField(max_length=50, unique=True)),
                ("pickup_location", models.CharField(max_length=200)),
                ("delivery_location", models.CharField(max_length=200)),
                ("pickup_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vehicle_type_required", models.CharField(max_length=20)),
                (
                    "vehicle_capacity_required",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "requested_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quoted_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("assigned", "Vehicle Assigned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_shipment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.shipment",
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.vehicle",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_bookings",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transport Booking",
                "verbose_name_plural": "Transport Bookings",
                "db_table": "transport_bookings",
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="logistics.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="FPOFleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_vehicles", models.IntegerField(default=0)),
                ("owned_vehicles", models.IntegerField(default=0)),
                ("hired_vehicles", models.IntegerField(default=0)),
                (
                    "total_capacity_quintals",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_vehicle_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("total_trips_completed", models.IntegerField(default=0)),
                (
                    "total_distance_covered_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_trips_per_vehicle",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_transport_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_cost_per_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "average_cost_per_quintal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_maintenance_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("vehicles_under_maintenance", models.IntegerField(default=0)),
                (
                    "on_time_delivery_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fleet",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Fleet",
                "verbose_name_plural": "FPO Fleets",
                "db_table": "fpo_fleets",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateTimeField()),
                (
                    "delivered_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("receiver_name", models.CharField(max_length=200)),
                ("receiver_contact", models.CharField(max_length=10)),
                (
                    "receiver_signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("condition_on_delivery", models.TextField()),
                (
                    "damaged_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shortage_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "delivery_photos",
                    models.JSONField(default=list, help_text="List of photo URLs"),
                ),
                (
                    "pod_document",
                    models.FileField(blank=True, null=True, upload_to="pod/"),
                ),
                (
                    "delivery_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("delivery_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "db_table": "deliveries",
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_number"], name="vehicles_vehicle_07aa58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["is_available"], name="vehicles_is_avai_9fa2da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipment_number"], name="shipments_shipmen_67925e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipments_status_cda325_idx"),
        ),
    ]
