# Generated by Django 4.2.23 on 2025-12-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logisticspartner_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticspartner',
            options={'verbose_name': 'Logistics Partner', 'verbose_name_plural': 'Logistics Partners'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='logisticspartner',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST registration number', max_length=15),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='service_states',
            field=models.JSONField(blank=True, default=list, help_text='States where service is available'),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='transport_license',
            field=models.CharField(blank=True, help_text='Transport license number', max_length=50),
        ),
        migrations.AddField(
            model_name='logisticspartner',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict, help_text='Uploaded verification documents'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_image',
            field=models.ImageField(blank=True, help_text='Proof of Delivery', null=True, upload_to='shipments/pod/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quoted freight charges', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_signature',
            field=models.ImageField(blank=True, null=True, upload_to='shipments/signatures/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='scheduled_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='scheduled_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Currently available for booking'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/pollution/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_document',
            field=models.FileField(blank=True, help_text='Registration Certificate', null=True, upload_to='vehicles/rc/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logisticspartner',
            name='company_name',
            field=models.CharField(help_text='Company/Business name', max_length=200),
        ),
        migrations.AlterField(
            model_name='logisticspartner',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified status'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted by Logistics'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_quintals',
            field=models.DecimalField(decimal_places=2, help_text='Cargo capacity in quintals', max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(help_text='Vehicle registration number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('mini_truck', 'Mini Truck (< 1 Ton)'), ('small_truck', 'Small Truck (1-3 Tons)'), ('medium_truck', 'Medium Truck (3-7 Tons)'), ('large_truck', 'Large Truck (7-15 Tons)'), ('trailer', 'Trailer (> 15 Tons)'), ('tempo', 'Tempo')], max_length=50),
        ),
    ]
