# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_name", models.CharField(max_length=200)),
                ("template_code", models.CharField(max_length=50, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather Alert"),
                            ("price", "Price Alert"),
                            ("payment", "Payment Confirmation"),
                            ("meeting", "Meeting Reminder"),
                            ("training", "Training Invitation"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "sms_content",
                    models.TextField(
                        help_text="SMS template (160 chars)", max_length=160
                    ),
                ),
                ("email_content", models.TextField(help_text="Email HTML template")),
                (
                    "push_content",
                    models.TextField(help_text="Push notification content"),
                ),
                ("whatsapp_content", models.TextField(blank=True)),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of variables: ['farmer_name', 'amount', ...]",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("te", "Telugu"),
                            ("ta", "Tamil"),
                            ("kn", "Kannada"),
                            ("mr", "Marathi"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "db_table": "message_templates",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather Alert"),
                            ("price", "Price Alert"),
                            ("advisory", "Advisory"),
                            ("payment", "Payment Confirmation"),
                            ("meeting", "Meeting Reminder"),
                            ("event", "Event Notification"),
                            ("announcement", "FPO Announcement"),
                            ("procurement", "Procurement Update"),
                            ("quality", "Quality Alert"),
                            ("training", "Training Invitation"),
                            ("subsidy", "Subsidy Update"),
                            ("loan", "Loan Update"),
                            ("general", "General Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="List of channels to send through"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.JSONField(
                        default=dict,
                        help_text="Status per channel: {'sms': 'delivered', 'email': 'failed'}",
                    ),
                ),
                ("action_url", models.URLField(blank=True)),
                ("action_data", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FPOAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting Announcement"),
                            ("procurement", "Procurement Notice"),
                            ("payment", "Payment Announcement"),
                            ("event", "Event Announcement"),
                            ("training", "Training Program"),
                            ("policy", "Policy Update"),
                            ("general", "General Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("target_all_members", models.BooleanField(default=True)),
                ("target_board_members", models.BooleanField(default=False)),
                ("send_via_sms", models.BooleanField(default=True)),
                ("send_via_email", models.BooleanField(default=False)),
                ("send_via_whatsapp", models.BooleanField(default=False)),
                ("send_via_app", models.BooleanField(default=True)),
                (
                    "attachments",
                    models.JSONField(default=list, help_text="List of attachment URLs"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("read_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "target_specific_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_announcements",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Announcement",
                "verbose_name_plural": "FPO Announcements",
                "db_table": "fpo_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-App Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(help_text="Phone/Email/Device ID", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.TextField(blank=True)),
                ("gateway_message_id", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Cost in INR",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Log",
                "verbose_name_plural": "Delivery Logs",
                "db_table": "delivery_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.CharField(max_length=200)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather-based"),
                            ("price", "Price-based"),
                            ("inventory", "Inventory-based"),
                            ("quality", "Quality-based"),
                            ("payment", "Payment-based"),
                            ("time", "Time-based"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("condition_field", models.CharField(max_length=100)),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("greater_than", "Greater Than"),
                            ("less_than", "Less Than"),
                            ("between", "Between"),
                            ("contains", "Contains"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_value", models.CharField(max_length=200)),
                (
                    "recipient_groups",
                    models.JSONField(
                        default=list, help_text="List of user groups to notify"
                    ),
                ),
                ("notification_channels", models.JSONField(default=list)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_triggered", models.IntegerField(default=0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.messagetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "db_table": "alert_rules",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["scheduled_for"], name="notificatio_schedul_3d00b6_idx"
            ),
        ),
    ]
