# Generated by Django 4.2.26 on 2025-11-22 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_number', models.CharField(max_length=100)),
                ('khasra_number', models.CharField(blank=True, max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='In hectares', max_digits=10)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('ulpin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ownership_type', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_source', models.CharField(blank=True, max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to='users.farmerprofile')),
            ],
            options={
                'db_table': 'land_records',
            },
        ),
        migrations.CreateModel(
            name='SoilHealthData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_date', models.DateField()),
                ('testing_lab', models.CharField(blank=True, max_length=200)),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('organic_carbon', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('nitrogen', models.CharField(max_length=20)),
                ('phosphorus', models.CharField(max_length=20)),
                ('potassium', models.CharField(max_length=20)),
                ('sulphur', models.CharField(blank=True, max_length=20)),
                ('zinc', models.CharField(blank=True, max_length=20)),
                ('iron', models.CharField(blank=True, max_length=20)),
                ('fertilizer_recommendations', models.JSONField(default=dict)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='users.farmerprofile')),
                ('land_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.landrecord')),
            ],
            options={
                'db_table': 'soil_health_data',
            },
        ),
        migrations.CreateModel(
            name='SatelliteImagery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capture_date', models.DateField()),
                ('satellite_source', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('ndvi_value', models.DecimalField(decimal_places=4, help_text='Normalized Difference Vegetation Index', max_digits=5, null=True)),
                ('ndwi_value', models.DecimalField(decimal_places=4, help_text='Water stress', max_digits=5, null=True)),
                ('crop_health_score', models.DecimalField(decimal_places=2, help_text='AI-calculated 0-100', max_digits=5, null=True)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('anomaly_type', models.CharField(blank=True, max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_images', to='users.farmerprofile')),
                ('land_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.landrecord')),
            ],
            options={
                'db_table': 'satellite_imagery',
            },
        ),
        migrations.CreateModel(
            name='ExternalAPILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_name', models.CharField(choices=[('IMD', 'India Meteorological Department'), ('AGMARKNET', 'Agricultural Marketing Information'), ('ISRO', 'Satellite Imagery'), ('AGRISTACK', 'Agri-Stack Portal'), ('PMFBY', 'Crop Insurance'), ('OTHERS', 'Others')], max_length=50)),
                ('endpoint', models.URLField()),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField()),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_time', models.IntegerField(help_text='In milliseconds')),
            ],
            options={
                'db_table': 'external_api_logs',
                'indexes': [models.Index(fields=['api_name', 'created_at'], name='external_ap_api_nam_acae87_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgriStackSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(max_length=50)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('synced_data', models.JSONField(default=dict)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agristack_syncs', to='users.farmerprofile')),
            ],
            options={
                'db_table': 'agristack_syncs',
            },
        ),
    ]
