# Generated by Django 4.2.23 on 2025-12-04 19:05

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Format: +919XXXXXXXXX', max_length=15, unique=True, validators=[apps.core.validators.validate_indian_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer (किसान)'), ('fpo', 'FPO (किसान उत्पादक संगठन)'), ('processor', 'Processor (प्रोसेसर)'), ('retailer', 'Retailer (खुदरा विक्रेता)'), ('logistics', 'Logistics (रसद)'), ('warehouse', 'Warehouse (भंडारण)'), ('government', 'Government Official (सरकारी अधिकारी)')], max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Phone number verified via OTP')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('aadhaar_number', models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, validators=[apps.core.validators.validate_aadhaar])),
                ('pan_number', models.CharField(blank=True, help_text='PAN format: ABCDE1234F', max_length=10, validators=[apps.core.validators.validate_pan])),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6, validators=[apps.core.validators.validate_pincode])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='hi', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=15, validators=[apps.core.validators.validate_indian_phone])),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
