# Generated by Django 4.2.23 on 2025-12-04 22:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='10-digit mobile number starting with 6-9 (e.g., 9137966960). No need to add +91.', max_length=15, unique=True, validators=[apps.core.validators.validate_indian_phone]),
        ),
    ]
