# Generated by Django 4.2.26 on 2025-11-22 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_id', models.CharField(max_length=50, unique=True)),
                ('area_planted', models.DecimalField(decimal_places=2, help_text='In hectares', max_digits=10)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('predicted_yield', models.DecimalField(decimal_places=2, help_text='In quintals', max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(decimal_places=2, help_text='In quintals', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SOWING', 'Sowing'), ('GROWING', 'Growing'), ('HARVESTING', 'Harvesting'), ('HARVESTED', 'Harvested'), ('FAILED', 'Failed')], default='PLANNED', max_length=20)),
                ('ai_recommendation_score', models.DecimalField(decimal_places=2, help_text='0-100', max_digits=5, null=True)),
            ],
            options={
                'db_table': 'crop_cycles',
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('ideal_temperature_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_temperature_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ideal_rainfall', models.DecimalField(decimal_places=2, help_text='In mm', max_digits=6)),
                ('growing_season', models.CharField(max_length=50)),
                ('maturity_days', models.IntegerField(help_text='Days to harvest')),
            ],
            options={
                'db_table': 'crop_types',
            },
        ),
        migrations.CreateModel(
            name='PestDiseaseDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='pest_images/')),
                ('detected_pest', models.CharField(max_length=200)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence 0-100', max_digits=5)),
                ('treatment_recommendation', models.TextField()),
                ('severity_level', models.CharField(max_length=20)),
                ('is_treated', models.BooleanField(default=False)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_detections', to='advisory.cropcycle')),
            ],
            options={
                'db_table': 'pest_disease_detections',
            },
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advisory.croptype'),
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='users.farmerprofile'),
        ),
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisory_type', models.CharField(choices=[('SOWING', 'Sowing Advisory'), ('IRRIGATION', 'Irrigation Advisory'), ('FERTILIZER', 'Fertilizer Recommendation'), ('HARVEST', 'Harvest Timing'), ('MARKET', 'Market Advisory')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('ai_confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_sources', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('farmer_feedback', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('crop_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advisory.cropcycle')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='users.farmerprofile')),
            ],
            options={
                'db_table': 'crop_advisories',
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_till', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('source', models.CharField(default='IMD', max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='users.farmerprofile')),
            ],
            options={
                'db_table': 'weather_alerts',
                'indexes': [models.Index(fields=['farmer', 'is_read'], name='weather_ale_farmer__c7cb3c_idx'), models.Index(fields=['valid_from'], name='weather_ale_valid_f_57a187_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cropcycle',
            index=models.Index(fields=['farmer', 'status'], name='crop_cycles_farmer__b5fe68_idx'),
        ),
        migrations.AddIndex(
            model_name='cropcycle',
            index=models.Index(fields=['sowing_date'], name='crop_cycles_sowing__0e0890_idx'),
        ),
        migrations.AddIndex(
            model_name='cropadvisory',
            index=models.Index(fields=['farmer', 'is_read'], name='crop_adviso_farmer__6bcedb_idx'),
        ),
    ]
