# Generated by Django 4.2.26 on 2025-11-26 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In quintals', max_digits=10)),
                ('quality_grade', models.CharField(max_length=10)),
                ('moisture_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oil_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_certificate_url', models.URLField(blank=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='advisory.cropcycle')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farmerprofile')),
            ],
            options={
                'db_table': 'batches',
            },
        ),
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('tested_by', models.CharField(max_length=200)),
                ('test_location', models.CharField(max_length=200)),
                ('moisture_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oil_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foreign_matter', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('damaged_seeds', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('final_grade', models.CharField(max_length=10)),
                ('is_passed', models.BooleanField(default=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='traceability.batch')),
            ],
            options={
                'db_table': 'quality_tests',
            },
        ),
        migrations.CreateModel(
            name='ProductTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('processing_date', models.DateField()),
                ('product_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('net_weight', models.DecimalField(decimal_places=2, help_text='In liters/kg', max_digits=8)),
                ('packaging_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('fssai_license', models.CharField(max_length=14)),
                ('is_organic_certified', models.BooleanField(default=False)),
                ('consumer_qr_code', models.ImageField(blank=True, null=True, upload_to='product_qr/')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.processorprofile')),
                ('source_batches', models.ManyToManyField(related_name='products', to='traceability.batch')),
            ],
            options={
                'db_table': 'product_traces',
            },
        ),
        migrations.CreateModel(
            name='SupplyChainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('HARVESTED', 'Harvested'), ('STORED_FARM', 'Stored at Farm'), ('COLLECTED_FPO', 'Collected by FPO'), ('STORED_FPO', 'Stored at FPO Warehouse'), ('DISPATCHED', 'Dispatched to Processor'), ('RECEIVED_PROCESSOR', 'Received at Processor'), ('PROCESSING_STARTED', 'Processing Started'), ('PROCESSING_COMPLETED', 'Processing Completed'), ('DISPATCHED_RETAIL', 'Dispatched to Retailer'), ('RECEIVED_RETAIL', 'Received at Retail')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('supporting_documents', models.JSONField(default=list)),
                ('blockchain_hash', models.CharField(blank=True, max_length=256)),
                ('actor_farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.farmerprofile')),
                ('actor_fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fpoprofile')),
                ('actor_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.processorprofile')),
                ('actor_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.retailerprofile')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traceability.batch')),
            ],
            options={
                'db_table': 'supply_chain_events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['batch', 'timestamp'], name='supply_chai_batch_i_9c4f59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_id'], name='batches_batch_i_72ed3d_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farmer', 'harvest_date'], name='batches_farmer__b8ba7b_idx'),
        ),
    ]
