# Generated by Django 4.2.27 on 2025-12-07 19:44

import apps.core.validators
import apps.lots.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpos', '0001_initial'),
        ('farmers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=apps.lots.models.lot_image_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lot Image',
                'verbose_name_plural': 'Lot Images',
                'db_table': 'lot_images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('additional_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Lot Status History',
                'verbose_name_plural': 'Lot Status Histories',
                'db_table': 'lot_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lot_number', models.CharField(editable=False, help_text='Auto-generated unique lot number', max_length=50, unique=True)),
                ('managed_by_fpo', models.BooleanField(default=False, help_text='True if farmer is FPO member and lot is auto-managed by FPO')),
                ('listing_type', models.CharField(choices=[('individual', 'Individual Farmer Lot'), ('fpo_managed', 'FPO Managed Lot'), ('fpo_aggregated', 'FPO Aggregated Bulk Lot')], default='individual', help_text='Type of listing', max_length=20)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], max_length=50)),
                ('crop_master_code', models.CharField(blank=True, help_text='Government-registered crop code (e.g., MUSTARD01)', max_length=50)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('crop_variety_code', models.CharField(blank=True, help_text='Government-approved variety code (e.g., MUS-PBOLD)', max_length=50)),
                ('harvest_date', models.DateField()),
                ('quantity_quintals', models.DecimalField(decimal_places=2, help_text='Total quantity available in quintals', max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('available_quantity_quintals', models.DecimalField(decimal_places=2, help_text='Remaining quantity available', max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('quality_grade', models.CharField(blank=True, choices=[('A+', 'A+ Grade (Premium)'), ('A', 'A Grade (Good)'), ('B', 'B Grade (Average)'), ('C', 'C Grade (Below Average)')], max_length=3, null=True)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture content percentage', max_digits=5, null=True)),
                ('oil_content', models.DecimalField(blank=True, decimal_places=2, help_text='Oil content percentage', max_digits=5, null=True)),
                ('expected_price_per_quintal', models.DecimalField(decimal_places=2, help_text="Farmer's expected price in ₹ per quintal", max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('final_price_per_quintal', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price', max_digits=10, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_address', models.TextField(blank=True, help_text='Address for pickup')),
                ('status', models.CharField(choices=[('available', 'Available'), ('bidding', 'Bidding Active'), ('sold', 'Sold'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('aggregated', 'Aggregated into Bulk Lot')], default='available', max_length=20)),
                ('listed_date', models.DateTimeField(auto_now_add=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the lot')),
                ('storage_conditions', models.CharField(blank=True, help_text='How the produce is currently stored', max_length=200)),
                ('organic_certified', models.BooleanField(default=False)),
                ('qr_code_url', models.URLField(blank=True, help_text='URL to generated QR code image')),
                ('blockchain_tx_id', models.CharField(blank=True, help_text='Blockchain transaction ID', max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('bid_count', models.IntegerField(default=0)),
                ('farmer', models.ForeignKey(blank=True, help_text='Farmer who created the lot. NULL for FPO-aggregated lots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farmers.farmerprofile')),
                ('fpo', models.ForeignKey(blank=True, help_text='FPO that procured this lot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procured_lots', to='fpos.fpoprofile')),
                ('parent_lots', models.ManyToManyField(blank=True, help_text='Parent lots for FPO aggregated listings (traceability)', related_name='aggregated_lots', to='lots.procurementlot')),
                ('source_warehouses', models.ManyToManyField(blank=True, help_text='Source warehouses for multi-warehouse aggregated lots', related_name='aggregated_from_lots', to='fpos.fpowarehouse')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse where this lot is stored (for FPO lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_lots', to='fpos.fpowarehouse')),
            ],
            options={
                'verbose_name': 'Procurement Lot',
                'verbose_name_plural': 'Procurement Lots',
                'db_table': 'procurement_lots',
                'ordering': ['-listed_date'],
            },
        ),
    ]
