# Generated by Django 4.2.7 on 2025-12-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmerprofile_state'),
        ('fpos', '0002_alter_fpoprofile_state_alter_fpowarehouse_state'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementlot',
            name='crop_master_code',
            field=models.CharField(blank=True, help_text='Government-registered crop code (e.g., MUSTARD01)', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='crop_variety_code',
            field=models.CharField(blank=True, help_text='Government-approved variety code (e.g., MUS-PBOLD)', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='listing_type',
            field=models.CharField(choices=[('individual', 'Individual Farmer Lot'), ('fpo_managed', 'FPO Managed Lot'), ('fpo_aggregated', 'FPO Aggregated Bulk Lot')], default='individual', help_text='Type of listing', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='managed_by_fpo',
            field=models.BooleanField(default=False, help_text='True if farmer is FPO member and lot is auto-managed by FPO'),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='parent_lots',
            field=models.ManyToManyField(blank=True, help_text='Parent lots for FPO aggregated listings (traceability)', related_name='aggregated_lots', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='source_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Source warehouses for multi-warehouse aggregated lots', related_name='aggregated_from_lots', to='fpos.fpowarehouse'),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this lot is stored (for FPO lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_lots', to='fpos.fpowarehouse'),
        ),
        migrations.AlterField(
            model_name='procurementlot',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer who created the lot. NULL for FPO-aggregated lots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farmers.farmerprofile'),
        ),
        migrations.AlterField(
            model_name='procurementlot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('bidding', 'Bidding Active'), ('sold', 'Sold'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('aggregated', 'Aggregated into Bulk Lot')], default='available', max_length=20),
        ),
    ]
