# Generated by Django 4.2.7 on 2025-12-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
    ]
