# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotstatushistory',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='lotimage',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lots.procurementlot'),
        ),
        migrations.AddIndex(
            model_name='procurementlot',
            index=models.Index(fields=['status', 'crop_type'], name='procurement_status_2360cb_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementlot',
            index=models.Index(fields=['farmer', 'status'], name='procurement_farmer__33f665_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementlot',
            index=models.Index(fields=['listed_date'], name='procurement_listed__6cc9ee_idx'),
        ),
    ]
