# Generated by Django 4.2.7 on 2025-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementlot',
            name='listing_type',
            field=models.CharField(choices=[('individual', 'Individual Farmer Lot'), ('fpo_managed', 'FPO Managed Lot'), ('fpo_aggregated', 'FPO Aggregated Bulk Lot')], default='individual', help_text='Type of listing', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='managed_by_fpo',
            field=models.BooleanField(default=False, help_text='True if farmer is FPO member and lot is auto-managed by FPO'),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='parent_lots',
            field=models.ManyToManyField(blank=True, help_text='Parent lots for FPO aggregated listings (traceability)', related_name='aggregated_lots', to='lots.procurementlot'),
        ),
    ]
