# Generated by Django 4.2.7 on 2025-12-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_procurementlot_crop_master_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementlot',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ Grade (Premium)'), ('A', 'A Grade (Good)'), ('B', 'B Grade (Average)'), ('C', 'C Grade (Below Average)')], max_length=3, null=True),
        ),
    ]
