# Generated by Django 4.2.7 on 2025-12-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        ('lots', '0002_procurementlot_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementlot',
            name='source_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Source warehouses for multi-warehouse aggregated lots', related_name='aggregated_from_lots', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this lot is stored (for FPO lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_lots', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='procurementlot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('bidding', 'Bidding Active'), ('sold', 'Sold'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('aggregated', 'Aggregated into Bulk Lot')], default='available', max_length=20),
        ),
    ]
