# Generated by Django 4.2.7 on 2025-12-07 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpos', '0002_alter_fpoprofile_state_alter_fpowarehouse_state'),
        ('lots', '0003_procurementlot_source_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementlot',
            name='source_warehouses',
            field=models.ManyToManyField(blank=True, help_text='Source warehouses for multi-warehouse aggregated lots', related_name='aggregated_from_lots', to='fpos.fpowarehouse'),
        ),
        migrations.AlterField(
            model_name='procurementlot',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this lot is stored (for FPO lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_lots', to='fpos.fpowarehouse'),
        ),
    ]
