# Generated by Django 4.2.23 on 2025-12-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_procurementlot_source_warehouses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementlot',
            name='crop_master_code',
            field=models.CharField(blank=True, help_text='Government-registered crop code (e.g., MUSTARD01)', max_length=50),
        ),
        migrations.AddField(
            model_name='procurementlot',
            name='crop_variety_code',
            field=models.CharField(blank=True, help_text='Government-approved variety code (e.g., MUS-PBOLD)', max_length=50),
        ),
    ]
