# Generated by Django 4.2.7 on 2025-12-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmerprofile_state'),
        ('lots', '0004_alter_procurementlot_source_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementlot',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer who created the lot. NULL for FPO-aggregated lots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='farmers.farmerprofile'),
        ),
    ]
