# Generated by Django 4.2.23 on 2025-12-07 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lots", "0004_procurementlot_crop_master_code_and_more"),
        ("lots", "0005_alter_procurementlot_farmer"),
    ]

    operations = []
