# Generated by Django 4.2.26 on 2025-12-01 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "retailer_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "retailer_type",
                    models.CharField(
                        choices=[
                            ("wholesaler", "Wholesaler"),
                            ("retail_chain", "Retail Chain"),
                            ("food_processor", "Food Processor"),
                            ("exporter", "Exporter"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("fssai_license", models.CharField(blank=True, max_length=14)),
                (
                    "monthly_requirement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly requirement in quintals",
                        max_digits=10,
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[6-9]\\d{9}$")
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("credit_15", "15 Days"),
                            ("credit_30", "30 Days"),
                        ],
                        default="credit_15",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retailer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "retailers",
                "indexes": [
                    models.Index(
                        fields=["retailer_code"], name="retailers_retaile_5d8c9c_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="retailers_city_6a47d9_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="retailers_is_veri_588551_idx",
                    ),
                ],
            },
        ),
    ]
