# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CropMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("scientific_name", models.CharField(max_length=150)),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("oilseed", "Oilseed"),
                            ("cereal", "Cereal"),
                            ("pulse", "Pulse"),
                        ],
                        default="oilseed",
                        max_length=20,
                    ),
                ),
                ("hindi_name", models.CharField(max_length=100)),
                (
                    "regional_names",
                    models.JSONField(
                        default=dict,
                        help_text="{'te': 'Telugu name', 'mr': 'Marathi name', ...}",
                    ),
                ),
                (
                    "suitable_seasons",
                    models.JSONField(
                        default=list, help_text="['kharif', 'rabi', 'zaid']"
                    ),
                ),
                ("suitable_soil_types", models.JSONField(default=list)),
                (
                    "water_requirement",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_duration_days",
                    models.IntegerField(help_text="Minimum crop duration in days"),
                ),
                (
                    "max_duration_days",
                    models.IntegerField(help_text="Maximum crop duration in days"),
                ),
                (
                    "average_yield_per_acre",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average yield in quintals per acre",
                        max_digits=8,
                    ),
                ),
                (
                    "oil_content_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Oil content percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "current_msp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current MSP per quintal in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "crop_image",
                    models.ImageField(blank=True, null=True, upload_to="crops/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Crop Master",
                "verbose_name_plural": "Crop Master",
                "db_table": "crop_master",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="YieldBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("agro_climatic_zone", models.CharField(blank=True, max_length=100)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                            ("annual", "Annual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "average_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average yield in quintals per acre",
                        max_digits=8,
                    ),
                ),
                (
                    "high_yield",
                    models.DecimalField(
                        decimal_places=2, help_text="High yield benchmark", max_digits=8
                    ),
                ),
                (
                    "low_yield",
                    models.DecimalField(
                        decimal_places=2, help_text="Low yield benchmark", max_digits=8
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        help_text="Data source: DES, State Agri Dept, etc.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_benchmarks",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yield Benchmark",
                "verbose_name_plural": "Yield Benchmarks",
                "db_table": "yield_benchmarks",
                "unique_together": {("crop", "state", "district", "season", "year")},
            },
        ),
        migrations.CreateModel(
            name="MSPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketing_season",
                    models.CharField(help_text="e.g., 2023-24", max_length=10),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[("kharif", "Kharif"), ("rabi", "Rabi")], max_length=10
                    ),
                ),
                (
                    "msp_per_quintal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="MSP in INR per quintal",
                        max_digits=10,
                    ),
                ),
                (
                    "increase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "increase_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notification_number", models.CharField(blank=True, max_length=100)),
                ("notification_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msp_records",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "MSP Record",
                "verbose_name_plural": "MSP Records",
                "db_table": "msp_records",
                "ordering": ["-marketing_season"],
                "unique_together": {("crop", "marketing_season", "season_type")},
            },
        ),
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mandi_name", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("price_date", models.DateField(db_index=True)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "arrivals",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Arrivals in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("agmarknet", "Agmarknet"),
                            ("enam", "e-NAM"),
                            ("manual", "Manual Entry"),
                        ],
                        default="agmarknet",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandi_prices",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandi Price",
                "verbose_name_plural": "Mandi Prices",
                "db_table": "mandi_prices",
                "indexes": [
                    models.Index(
                        fields=["price_date"], name="mandi_price_price_d_e74f3a_idx"
                    ),
                    models.Index(
                        fields=["district", "state"],
                        name="mandi_price_distric_a60171_idx",
                    ),
                ],
                "unique_together": {("crop", "mandi_name", "price_date")},
            },
        ),
        migrations.CreateModel(
            name="CropVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variety_name", models.CharField(max_length=100)),
                ("variety_code", models.CharField(max_length=50, unique=True)),
                (
                    "developed_by",
                    models.CharField(
                        help_text="e.g., ICAR, State Agricultural University",
                        max_length=200,
                    ),
                ),
                ("release_year", models.IntegerField()),
                ("duration_days", models.IntegerField()),
                (
                    "yield_potential",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yield potential in quintals per acre",
                        max_digits=8,
                    ),
                ),
                ("oil_content", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "disease_resistance",
                    models.JSONField(
                        default=list, help_text="List of diseases resistant to"
                    ),
                ),
                (
                    "pest_resistance",
                    models.JSONField(
                        default=list, help_text="List of pests resistant to"
                    ),
                ),
                ("suitable_states", models.JSONField(default=list)),
                ("suitable_agro_zones", models.JSONField(default=list)),
                (
                    "seed_rate_per_acre",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Seed rate in kg per acre",
                        max_digits=6,
                    ),
                ),
                ("special_features", models.TextField(blank=True)),
                ("is_recommended", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Variety",
                "verbose_name_plural": "Crop Varieties",
                "db_table": "crop_varieties",
                "unique_together": {("crop", "variety_name")},
            },
        ),
    ]
