# Generated by Django 4.2.23 on 2025-12-04 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_code', models.CharField(max_length=20, unique=True)),
                ('crop_name', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], max_length=50)),
                ('hindi_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('oil_content_percentage', models.DecimalField(decimal_places=2, help_text='Average oil content %', max_digits=5)),
                ('growing_season', models.JSONField(default=list, help_text='Suitable seasons for cultivation')),
                ('maturity_days', models.IntegerField(help_text='Days to maturity', validators=[django.core.validators.MinValueValidator(1)])),
                ('water_requirement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('suitable_soil_types', models.JSONField(default=list, help_text='List of suitable soil types')),
                ('suitable_states', models.JSONField(default=list, help_text='Major producing states')),
                ('description', models.TextField(blank=True)),
                ('cultivation_tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/master/')),
            ],
            options={
                'verbose_name': 'Crop Master',
                'verbose_name_plural': 'Crop Master Data',
                'db_table': 'crop_master',
            },
        ),
        migrations.CreateModel(
            name='MSPRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], max_length=50)),
                ('year', models.IntegerField(help_text='Marketing year (e.g., 2024 for 2024-25)')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (खरीफ) - June to October'), ('rabi', 'Rabi (रबी) - November to March'), ('zaid', 'Zaid (जायद) - March to June')], max_length=20)),
                ('msp_per_quintal', models.DecimalField(decimal_places=2, help_text='MSP in ₹ per quintal', max_digits=10)),
                ('bonus_per_quintal', models.DecimalField(decimal_places=2, default=0, help_text='Additional bonus if any', max_digits=10)),
                ('notification_number', models.CharField(blank=True, max_length=100)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MSP Record',
                'verbose_name_plural': 'MSP Records',
                'db_table': 'msp_records',
                'ordering': ['-year', '-effective_from'],
                'unique_together': {('crop_type', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], max_length=50)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, help_text='Most common selling price', max_digits=10)),
                ('arrival_quantity_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(choices=[('enam', 'eNAM'), ('agmarknet', 'AgMarkNet'), ('manual', 'Manual Entry')], default='eNAM', max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Mandi Price',
                'verbose_name_plural': 'Mandi Prices',
                'db_table': 'mandi_prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['crop_type', 'state', 'date'], name='mandi_price_crop_ty_01feae_idx'), models.Index(fields=['date'], name='mandi_price_date_3cb61d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variety_name', models.CharField(max_length=100)),
                ('variety_code', models.CharField(max_length=50, unique=True)),
                ('maturity_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('yield_potential_quintals_per_acre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oil_content_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (खरीफ) - June to October'), ('rabi', 'Rabi (रबी) - November to March'), ('zaid', 'Zaid (जायद) - March to June')], max_length=20)),
                ('suitable_regions', models.JSONField(default=list)),
                ('disease_resistance', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('seed_rate_kg_per_acre', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.cropmaster')),
            ],
            options={
                'verbose_name': 'Crop Variety',
                'verbose_name_plural': 'Crop Varieties',
                'db_table': 'crop_varieties',
            },
        ),
    ]
