# Generated by Django 4.2.26 on 2025-12-01 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "crop_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "crop_type",
                    models.CharField(
                        choices=[
                            ("groundnut", "Groundnut (Peanut)"),
                            ("mustard", "Mustard"),
                            ("sunflower", "Sunflower"),
                            ("soybean", "Soybean"),
                            ("sesame", "Sesame (Til)"),
                            ("safflower", "Safflower"),
                            ("castor", "Castor"),
                            ("linseed", "Linseed (Flaxseed)"),
                            ("niger", "Niger Seed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("variety", models.CharField(max_length=100)),
                (
                    "planted_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("planting_date", models.DateField()),
                ("expected_harvest_date", models.DateField()),
                ("actual_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_address", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planted", "Planted"),
                            ("growing", "Growing"),
                            ("flowering", "Flowering"),
                            ("matured", "Matured"),
                            ("harvested", "Harvested"),
                            ("processed", "Processed"),
                            ("sold", "Sold"),
                        ],
                        default="planted",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "oil_content_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("quality_grade", models.CharField(blank=True, max_length=10)),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        limit_choices_to={"role": "farmer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_crops",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HarvestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("harvest_date", models.DateField()),
                ("total_yield", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "oil_content",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("moisture_level", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "foreign_matter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("quality_grade", models.CharField(max_length=10)),
                ("storage_location", models.CharField(blank=True, max_length=255)),
                ("storage_method", models.CharField(blank=True, max_length=100)),
                ("organic_certified", models.BooleanField(default=False)),
                ("certification_number", models.CharField(blank=True, max_length=100)),
                (
                    "market_price_per_quintal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_record",
                        to="crops.crop",
                    ),
                ),
                (
                    "harvested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("farmer_to_fpo", "Farmer to FPO"),
                            ("fpo_to_processor", "FPO to Processor"),
                            ("fpo_to_retailer", "FPO to Retailer"),
                            ("processor_to_retailer", "Processor to Retailer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "blockchain_hash",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("previous_hash", models.CharField(blank=True, max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="crops.crop",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="CropPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("yield", "Yield Prediction"),
                            ("disease", "Disease Detection"),
                            ("quality", "Quality Assessment"),
                            ("market_price", "Market Price Forecast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                ("predicted_value", models.JSONField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("model_version", models.CharField(max_length=50)),
                ("input_features", models.JSONField()),
                ("actual_value", models.JSONField(blank=True, null=True)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.CreateModel(
            name="CropObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_date", models.DateField()),
                (
                    "plant_height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("leaf_color", models.CharField(blank=True, max_length=50)),
                ("pest_infestation", models.BooleanField(default=False)),
                ("disease_detected", models.BooleanField(default=False)),
                ("disease_name", models.CharField(blank=True, max_length=150)),
                (
                    "soil_moisture",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rainfall",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="crop_observations/"
                    ),
                ),
                ("ai_analysis_result", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="crops.crop",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-observation_date"],
            },
        ),
        migrations.CreateModel(
            name="CropInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("fertilizer", "Fertilizer"),
                            ("pesticide", "Pesticide"),
                            ("herbicide", "Herbicide"),
                            ("seed", "Seed"),
                            ("irrigation", "Irrigation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_name", models.CharField(max_length=150)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("application_date", models.DateField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-application_date"],
            },
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["farmer", "status"], name="crops_crop_farmer__074fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["crop_type", "state"], name="crops_crop_crop_ty_6562c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["planting_date"], name="crops_crop_plantin_b1d864_idx"
            ),
        ),
    ]
