<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-12-07 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmerprofile_state'),
        ('fpos', '0002_alter_fpoprofile_state_alter_fpowarehouse_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandiprice',
            name='state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50),
        ),
        migrations.CreateModel(
            name='CropVarietyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], help_text='Existing crop type', max_length=50)),
                ('variety_name', models.CharField(help_text='Name of new variety to add', max_length=100)),
                ('variety_code', models.CharField(blank=True, help_text='Optional: Official variety code if known', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Where is this variety from? (e.g., State Agriculture Dept, ICAR)', max_length=200)),
                ('reason', models.TextField(help_text='Why do you need this variety?')),
                ('characteristics', models.TextField(blank=True, help_text='Any known characteristics (maturity days, yield, etc.)')),
                ('region', models.CharField(blank=True, help_text='Suitable region/district', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Already Exists')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments/feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='crops.cropvariety')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variety_requests', to='farmers.farmerprofile')),
                ('fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variety_requests', to='fpos.fpoprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_variety_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Variety Request',
                'verbose_name_plural': 'Crop Variety Requests',
                'db_table': 'crop_variety_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='crop_variet_status_d58b04_idx'), models.Index(fields=['crop_type', 'status'], name='crop_variet_crop_ty_a49c91_idx')],
            },
        ),
    ]
=======
# Generated by Django 4.2.7 on 2025-12-07 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fpos', '0002_alter_fpoprofile_state_alter_fpowarehouse_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0003_alter_farmerprofile_state'),
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandiprice',
            name='state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50),
        ),
        migrations.CreateModel(
            name='CropVarietyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], help_text='Existing crop type', max_length=50)),
                ('variety_name', models.CharField(help_text='Name of new variety to add', max_length=100)),
                ('variety_code', models.CharField(blank=True, help_text='Optional: Official variety code if known', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Where is this variety from? (e.g., State Agriculture Dept, ICAR)', max_length=200)),
                ('reason', models.TextField(help_text='Why do you need this variety?')),
                ('characteristics', models.TextField(blank=True, help_text='Any known characteristics (maturity days, yield, etc.)')),
                ('region', models.CharField(blank=True, help_text='Suitable region/district', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Already Exists')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin comments/feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='crops.cropvariety')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variety_requests', to='farmers.farmerprofile')),
                ('fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variety_requests', to='fpos.fpoprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_variety_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Variety Request',
                'verbose_name_plural': 'Crop Variety Requests',
                'db_table': 'crop_variety_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='crop_variet_status_d58b04_idx'), models.Index(fields=['crop_type', 'status'], name='crop_variet_crop_ty_a49c91_idx')],
            },
        ),
    ]
>>>>>>> 084d2c75d1756420e92e0dd5654a0558b3c02a74
