# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0002_initial'),
        ('fpos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropvarietyrequest',
            name='fpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variety_requests', to='fpos.fpoprofile'),
        ),
    ]
