# Generated by Django 4.2.23 on 2025-12-07 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crops", "0002_alter_mandiprice_state"),
        ("crops", "0002_cropvarietyrequest"),
    ]

    operations = []
