# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropvarietyrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_variety_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.cropmaster'),
        ),
        migrations.AddIndex(
            model_name='cropvarietyrequest',
            index=models.Index(fields=['status', 'created_at'], name='crop_variet_status_d58b04_idx'),
        ),
        migrations.AddIndex(
            model_name='cropvarietyrequest',
            index=models.Index(fields=['crop_type', 'status'], name='crop_variet_crop_ty_a49c91_idx'),
        ),
    ]
