# Generated by Django 4.2.26 on 2025-11-29 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fpos", "0001_initial"),
        ("crops", "0001_initial"),
        ("farmers", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DividendDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distribution_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Dividend"),
                            ("interim", "Interim Dividend"),
                            ("bonus", "Bonus Share"),
                            ("patronage", "Patronage Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g., 2023-24", max_length=10),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net profit for the period in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "distributable_profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Profit available for distribution after reserves",
                        max_digits=15,
                    ),
                ),
                (
                    "allocated_to_reserve",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount allocated to reserves as per rules",
                        max_digits=12,
                    ),
                ),
                (
                    "allocated_to_operations",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount retained for operations",
                        max_digits=12,
                    ),
                ),
                (
                    "allocated_to_dividend",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for dividend distribution",
                        max_digits=12,
                    ),
                ),
                (
                    "dividend_rate_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dividend rate as % of share capital",
                        max_digits=5,
                    ),
                ),
                (
                    "dividend_per_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dividend amount per share in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "patronage_basis",
                    models.CharField(
                        choices=[
                            ("share_capital", "Based on Share Capital"),
                            ("transaction_volume", "Based on Transaction Volume"),
                            ("production_supplied", "Based on Production Supplied"),
                            ("combined", "Combined Method"),
                        ],
                        default="share_capital",
                        max_length=30,
                    ),
                ),
                (
                    "minimum_shareholding_required",
                    models.IntegerField(
                        default=1, help_text="Minimum shares to be eligible"
                    ),
                ),
                (
                    "minimum_membership_months",
                    models.IntegerField(
                        default=6, help_text="Minimum membership duration in months"
                    ),
                ),
                ("total_eligible_members", models.IntegerField()),
                ("members_paid", models.IntegerField(default=0)),
                ("members_pending", models.IntegerField(default=0)),
                ("tds_applicable", models.BooleanField(default=True)),
                (
                    "tds_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "total_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "declaration_date",
                    models.DateField(help_text="Date when dividend was declared"),
                ),
                ("board_approval_date", models.DateField(blank=True, null=True)),
                (
                    "record_date",
                    models.DateField(
                        help_text="Date to determine eligible shareholders"
                    ),
                ),
                (
                    "payment_start_date",
                    models.DateField(help_text="Date when payment starts"),
                ),
                (
                    "payment_end_date",
                    models.DateField(help_text="Target date to complete all payments"),
                ),
                ("agm_date", models.DateField(blank=True, null=True)),
                ("agm_resolution_number", models.CharField(blank=True, max_length=50)),
                (
                    "total_amount_disbursed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pending_disbursement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declared", "Declared"),
                            ("approved", "Approved by Board"),
                            ("processing", "Processing"),
                            ("disbursed", "Disbursed"),
                            ("partially_disbursed", "Partially Disbursed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="declared",
                        max_length=20,
                    ),
                ),
                ("payment_from_account", models.CharField(max_length=20)),
                ("payment_from_bank", models.CharField(max_length=100)),
                ("payment_from_ifsc", models.CharField(max_length=11)),
                (
                    "board_resolution",
                    models.FileField(
                        blank=True, null=True, upload_to="dividends/resolutions/"
                    ),
                ),
                (
                    "distribution_statement",
                    models.FileField(
                        blank=True, null=True, upload_to="dividends/statements/"
                    ),
                ),
                (
                    "tds_certificate_batch",
                    models.FileField(
                        blank=True,
                        help_text="Batch file of Form 16A",
                        null=True,
                        upload_to="dividends/tds_certs/",
                    ),
                ),
                ("declaration_remarks", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_dividends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_distributions",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_dividends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dividend Distribution",
                "verbose_name_plural": "Dividend Distributions",
                "db_table": "dividend_distributions",
                "ordering": ["-declaration_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_account_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_months", models.IntegerField()),
                ("emi_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "outstanding_principal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "outstanding_interest",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("next_due_date", models.DateField()),
                (
                    "overdue_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("days_overdue", models.IntegerField(default=0)),
                (
                    "penalty_charged",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("disbursement_date", models.DateField()),
                ("maturity_date", models.DateField()),
                ("actual_closure_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("overdue", "Overdue"),
                            ("npa", "NPA"),
                            ("closed", "Closed"),
                            ("written_off", "Written Off"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("total_emis", models.IntegerField()),
                ("emis_paid", models.IntegerField(default=0)),
                ("emis_overdue", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_accounts",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_accounts",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Account",
                "verbose_name_plural": "Loan Accounts",
                "db_table": "loan_accounts",
            },
        ),
        migrations.CreateModel(
            name="LoanScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheme_name", models.CharField(max_length=200)),
                ("scheme_code", models.CharField(max_length=20, unique=True)),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Bank/NBFC/Financial Institution", max_length=200
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("bank", "Commercial Bank"),
                            ("rrrb", "Regional Rural Bank"),
                            ("cooperative", "Cooperative Bank"),
                            ("nbfc", "NBFC"),
                            ("nabard", "NABARD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_beneficiary",
                    models.CharField(
                        choices=[
                            ("farmer", "Individual Farmer"),
                            ("fpo", "FPO"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("crop_loan", "Crop Loan"),
                            ("kcc", "Kisan Credit Card"),
                            ("term_loan", "Term Loan"),
                            ("working_capital", "Working Capital"),
                            ("machinery", "Machinery Purchase"),
                            ("warehouse", "Warehouse Construction"),
                            ("processing_unit", "Processing Unit"),
                            ("vehicle", "Vehicle Purchase"),
                            ("general", "General Purpose"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate %",
                        max_digits=5,
                    ),
                ),
                ("subsidized", models.BooleanField(default=False)),
                (
                    "subsidized_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("min_tenure_months", models.IntegerField()),
                ("max_tenure_months", models.IntegerField()),
                ("eligibility_criteria", models.TextField()),
                ("required_documents", models.JSONField(default=list)),
                ("collateral_required", models.BooleanField(default=True)),
                ("collateral_details", models.TextField(blank=True)),
                ("government_subsidized", models.BooleanField(default=False)),
                (
                    "subsidy_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "processing_fee_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("processing_time_days", models.IntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Loan Scheme",
                "verbose_name_plural": "Loan Schemes",
                "db_table": "loan_schemes",
            },
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("interest_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "penalty_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("auto_debit", "Auto Debit"),
                            ("online", "Online Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_reference", models.CharField(max_length=100)),
                (
                    "emi_number",
                    models.IntegerField(help_text="EMI number (1, 2, 3...)"),
                ),
                ("is_on_time", models.BooleanField(default=True)),
                ("days_late", models.IntegerField(default=0)),
                (
                    "payment_receipt",
                    models.FileField(blank=True, null=True, upload_to="loan_receipts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "loan_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="finance.loanaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Repayment",
                "verbose_name_plural": "Loan Repayments",
                "db_table": "loan_repayments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "loan_amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("loan_purpose", models.TextField()),
                ("tenure_months", models.IntegerField()),
                (
                    "repayment_mode",
                    models.CharField(
                        choices=[
                            ("emi", "EMI"),
                            ("bullet", "Bullet Payment"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="emi",
                        max_length=20,
                    ),
                ),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "existing_loans",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("collateral_offered", models.TextField(blank=True)),
                (
                    "collateral_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "documents_uploaded",
                    models.JSONField(
                        default=dict, help_text="Document name: file URL mapping"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("documents_pending", "Documents Pending"),
                            ("field_verification", "Field Verification"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                ("credit_assessment", models.TextField(blank=True)),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("approved_tenure", models.IntegerField(blank=True, null=True)),
                (
                    "approved_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("approved_by", models.CharField(blank=True, max_length=200)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "disbursement_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "disbursement_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "loan_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="finance.loanaccount",
                    ),
                ),
                (
                    "loan_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.loanscheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Application",
                "verbose_name_plural": "Loan Applications",
                "db_table": "loan_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="loanaccount",
            name="loan_scheme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.loanscheme"
            ),
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("pmfby", "Pradhan Mantri Fasal Bima Yojana"),
                            ("crop_insurance", "Crop Insurance"),
                            ("livestock_insurance", "Livestock Insurance"),
                            ("life_insurance", "Life Insurance"),
                            ("health_insurance", "Health Insurance"),
                        ],
                        max_length=30,
                    ),
                ),
                ("insurance_company", models.CharField(max_length=200)),
                ("season", models.CharField(blank=True, max_length=10)),
                ("year", models.IntegerField()),
                (
                    "insured_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Insured area in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "sum_insured",
                    models.DecimalField(
                        decimal_places=2, help_text="Sum insured in INR", max_digits=12
                    ),
                ),
                ("total_premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("farmer_share", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "government_subsidy",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("policy_start_date", models.DateField()),
                ("policy_end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("claimed", "Claimed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("claim_filed", models.BooleanField(default=False)),
                (
                    "claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("claim_status", models.CharField(blank=True, max_length=20)),
                (
                    "policy_document",
                    models.FileField(
                        blank=True, null=True, upload_to="insurance_policies/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farm_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmers.farmplot",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_policies",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Policy",
                "verbose_name_plural": "Insurance Policies",
                "db_table": "insurance_policies",
                "ordering": ["-policy_start_date"],
            },
        ),
        migrations.CreateModel(
            name="FPOLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_account_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "loan_application_number",
                    models.CharField(max_length=50, unique=True),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("working_capital", "Working Capital Loan"),
                            ("term_loan", "Term Loan"),
                            ("crop_loan", "Crop Loan"),
                            ("machinery_loan", "Machinery Purchase Loan"),
                            ("infrastructure_loan", "Infrastructure Development"),
                            ("warehouse_loan", "Warehouse Construction"),
                            ("vehicle_loan", "Vehicle Purchase"),
                            ("processing_unit_loan", "Processing Unit Setup"),
                            ("bridge_loan", "Bridge Loan"),
                            ("overdraft", "Cash Credit/Overdraft"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "loan_purpose",
                    models.TextField(help_text="Detailed purpose of loan"),
                ),
                (
                    "lending_institution",
                    models.CharField(
                        choices=[
                            ("nationalized_bank", "Nationalized Bank"),
                            ("cooperative_bank", "Cooperative Bank"),
                            ("regional_rural_bank", "Regional Rural Bank (RRB)"),
                            ("nabard", "NABARD"),
                            ("sfac", "SFAC"),
                            ("private_bank", "Private Bank"),
                            ("nbfc", "NBFC"),
                            ("microfinance", "Microfinance Institution"),
                        ],
                        max_length=30,
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("branch_name", models.CharField(max_length=200)),
                ("branch_ifsc", models.CharField(max_length=11)),
                ("loan_officer_name", models.CharField(max_length=200)),
                ("loan_officer_contact", models.CharField(max_length=10)),
                (
                    "loan_amount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loan amount applied for in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "loan_amount_sanctioned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sanctioned loan amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "loan_amount_disbursed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually disbursed",
                        max_digits=15,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate %",
                        max_digits=5,
                    ),
                ),
                (
                    "interest_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Rate"),
                            ("floating", "Floating Rate"),
                            ("subsidized", "Subsidized Rate"),
                        ],
                        default="floating",
                        max_length=20,
                    ),
                ),
                ("interest_subsidy_applicable", models.BooleanField(default=False)),
                (
                    "subsidized_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Effective interest rate after subsidy",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "tenure_months",
                    models.IntegerField(help_text="Loan tenure in months"),
                ),
                (
                    "moratorium_period_months",
                    models.IntegerField(
                        default=0, help_text="Moratorium period before repayment starts"
                    ),
                ),
                (
                    "repayment_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("yearly", "Yearly"),
                            ("bullet", "Bullet Payment"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "emi_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="EMI amount if applicable",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("application_date", models.DateField()),
                ("sanction_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("first_repayment_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "collateral_type",
                    models.CharField(
                        choices=[
                            ("land", "Land Mortgage"),
                            ("warehouse_receipt", "Warehouse Receipt"),
                            ("crop_hypothecation", "Crop Hypothecation"),
                            ("machinery", "Machinery Hypothecation"),
                            ("guarantee", "Personal Guarantee"),
                            ("cgtmse", "CGTMSE Guarantee"),
                            ("no_collateral", "No Collateral"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "collateral_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("collateral_details", models.TextField(blank=True)),
                ("guarantee_details", models.TextField(blank=True)),
                ("loan_insurance_applicable", models.BooleanField(default=False)),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "insurance_premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "disbursement_mode",
                    models.CharField(
                        choices=[
                            ("lump_sum", "Lump Sum"),
                            ("installments", "Installments"),
                        ],
                        default="lump_sum",
                        max_length=20,
                    ),
                ),
                ("number_of_disbursements", models.IntegerField(default=1)),
                ("disbursements_completed", models.IntegerField(default=0)),
                (
                    "total_amount_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "principal_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "interest_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outstanding_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "overdue_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("days_past_due", models.IntegerField(default=0)),
                (
                    "penalty_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Application Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("sanctioned", "Sanctioned"),
                            ("disbursed", "Disbursed"),
                            ("active", "Active/Ongoing"),
                            ("closed", "Closed/Repaid"),
                            ("overdue", "Overdue"),
                            ("npa", "Non-Performing Asset"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "credit_score_at_application",
                    models.IntegerField(blank=True, null=True),
                ),
                ("current_credit_score", models.IntegerField(blank=True, null=True)),
                (
                    "loan_application_form",
                    models.FileField(
                        blank=True, null=True, upload_to="loans/applications/"
                    ),
                ),
                (
                    "project_report",
                    models.FileField(blank=True, null=True, upload_to="loans/reports/"),
                ),
                (
                    "financial_statements",
                    models.FileField(
                        blank=True, null=True, upload_to="loans/financials/"
                    ),
                ),
                (
                    "sanction_letter",
                    models.FileField(
                        blank=True, null=True, upload_to="loans/sanction_letters/"
                    ),
                ),
                (
                    "loan_agreement",
                    models.FileField(
                        blank=True, null=True, upload_to="loans/agreements/"
                    ),
                ),
                (
                    "utilization_certificate_submitted",
                    models.BooleanField(default=False),
                ),
                (
                    "utilization_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="loans/utilization_certs/"
                    ),
                ),
                (
                    "repayment_performance_score",
                    models.IntegerField(
                        default=100, help_text="Performance score 0-100"
                    ),
                ),
                ("bank_remarks", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Loan",
                "verbose_name_plural": "FPO Loans",
                "db_table": "fpo_loans",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="Subsidy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "subsidy_type",
                    models.CharField(
                        choices=[
                            ("pm_kisan", "PM-KISAN"),
                            ("input_subsidy", "Input Subsidy (Seeds/Fertilizer)"),
                            ("drip_irrigation", "Drip Irrigation Subsidy"),
                            ("sprinkler", "Sprinkler System Subsidy"),
                            ("farm_mechanization", "Farm Mechanization"),
                            ("storage_subsidy", "Storage Infrastructure"),
                            ("processing_unit", "Processing Unit Setup"),
                            ("fpo_support", "FPO Formation Support"),
                            ("pmfby", "PMFBY Insurance Premium"),
                            (
                                "kisan_credit_card",
                                "Kisan Credit Card Interest Subvention",
                            ),
                            ("solar_pump", "Solar Pump Subsidy"),
                            ("organic_farming", "Organic Farming Support"),
                            ("msp_bonus", "MSP Bonus Payment"),
                            ("other", "Other Subsidy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("scheme_name", models.CharField(max_length=200)),
                ("scheme_code", models.CharField(blank=True, max_length=50)),
                (
                    "implementing_agency",
                    models.CharField(
                        choices=[
                            ("agriculture_dept", "State Agriculture Department"),
                            ("horticulture_dept", "Horticulture Department"),
                            ("nabard", "NABARD"),
                            ("sfac", "SFAC"),
                            ("ncdex", "NCDEX e-Markets"),
                            ("district_administration", "District Administration"),
                            ("central_govt", "Central Government"),
                        ],
                        max_length=30,
                    ),
                ),
                ("nodal_officer_name", models.CharField(blank=True, max_length=200)),
                ("nodal_officer_contact", models.CharField(blank=True, max_length=10)),
                (
                    "total_project_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total project/investment cost in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "subsidy_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subsidy percentage as per scheme",
                        max_digits=5,
                    ),
                ),
                (
                    "subsidy_amount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Subsidy amount applied for",
                        max_digits=12,
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approved subsidy amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually disbursed",
                        max_digits=12,
                    ),
                ),
                (
                    "beneficiary_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Beneficiary's own contribution",
                        max_digits=12,
                    ),
                ),
                ("application_date", models.DateField()),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "financial_year",
                    models.CharField(help_text="e.g., 2023-24", max_length=10),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("account_holder_name", models.CharField(max_length=200)),
                (
                    "application_form",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/applications/"
                    ),
                ),
                (
                    "project_report",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/reports/"
                    ),
                ),
                (
                    "quotations",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/quotations/"
                    ),
                ),
                (
                    "land_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/land_docs/"
                    ),
                ),
                (
                    "caste_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/caste_certs/"
                    ),
                ),
                (
                    "income_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/income_certs/"
                    ),
                ),
                (
                    "bank_passbook",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/bank_docs/"
                    ),
                ),
                (
                    "other_documents",
                    models.JSONField(
                        default=list, help_text="List of additional document URLs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Application Draft"),
                            ("submitted", "Application Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("disbursed", "Disbursed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approval_remarks", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("field_verification_done", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "verification_report",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="subsidies/verification_reports/",
                    ),
                ),
                (
                    "disbursement_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dbt", "Direct Benefit Transfer (DBT)"),
                            ("neft", "NEFT"),
                            ("rtgs", "RTGS"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=100)),
                (
                    "disbursement_receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/receipts/"
                    ),
                ),
                ("is_installment_based", models.BooleanField(default=False)),
                ("total_installments", models.IntegerField(default=1)),
                ("installments_disbursed", models.IntegerField(default=0)),
                ("utilization_certificate_required", models.BooleanField(default=True)),
                (
                    "utilization_certificate_submitted",
                    models.BooleanField(default=False),
                ),
                (
                    "utilization_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="subsidies/utilization_certs/"
                    ),
                ),
                ("subsidy_utilized", models.BooleanField(default=False)),
                (
                    "utilization_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("impact_assessment_done", models.BooleanField(default=False)),
                ("impact_report", models.TextField(blank=True)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("block", models.CharField(blank=True, max_length=100)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidies",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidies",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_subsidies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsidy",
                "verbose_name_plural": "Subsidies",
                "db_table": "subsidies",
                "ordering": ["-application_date"],
                "indexes": [
                    models.Index(
                        fields=["application_number"],
                        name="subsidies_applica_74fac0_idx",
                    ),
                    models.Index(fields=["status"], name="subsidies_status_1648cb_idx"),
                    models.Index(
                        fields=["subsidy_type"], name="subsidies_subsidy_2ecb6e_idx"
                    ),
                    models.Index(
                        fields=["financial_year"], name="subsidies_financi_d15833_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MemberDividendPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_number", models.CharField(max_length=20)),
                ("shares_held", models.IntegerField()),
                (
                    "share_value_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_share_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "gross_dividend",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_dividend", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer (NEFT/RTGS)"),
                            ("upi", "UPI"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                            ("reinvestment", "Reinvested in Shares"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("transaction_reference", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("ifsc_code", models.CharField(max_length=11)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("on_hold", "On Hold"),
                            ("reinvested", "Reinvested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                (
                    "tds_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Form 16A for this member",
                        null=True,
                        upload_to="dividends/member_tds/",
                    ),
                ),
                (
                    "payment_receipt",
                    models.FileField(
                        blank=True, null=True, upload_to="dividends/receipts/"
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledgment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dividend_distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_payments",
                        to="finance.dividenddistribution",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividend_payments",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Dividend Payment",
                "verbose_name_plural": "Member Dividend Payments",
                "db_table": "member_dividend_payments",
                "indexes": [
                    models.Index(
                        fields=["payment_status"], name="member_divi_payment_c3e352_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="member_divi_payment_8d9e1b_idx"
                    ),
                ],
                "unique_together": {("dividend_distribution", "farmer")},
            },
        ),
        migrations.AddIndex(
            model_name="loanaccount",
            index=models.Index(
                fields=["loan_account_number"], name="loan_accoun_loan_ac_ee7797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanaccount",
            index=models.Index(fields=["status"], name="loan_accoun_status_e06165_idx"),
        ),
        migrations.AddIndex(
            model_name="fpoloan",
            index=models.Index(
                fields=["loan_account_number"], name="fpo_loans_loan_ac_5e3d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpoloan",
            index=models.Index(fields=["status"], name="fpo_loans_status_ee798d_idx"),
        ),
        migrations.AddIndex(
            model_name="fpoloan",
            index=models.Index(
                fields=["maturity_date"], name="fpo_loans_maturit_7029c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddistribution",
            index=models.Index(
                fields=["distribution_number"], name="dividend_di_distrib_30843d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddistribution",
            index=models.Index(
                fields=["financial_year"], name="dividend_di_financi_18f000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dividenddistribution",
            index=models.Index(fields=["status"], name="dividend_di_status_7538cc_idx"),
        ),
    ]
