# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
        ("crops", "0001_initial"),
        ("farmers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "input_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Input quantity in quintals",
                        max_digits=12,
                    ),
                ),
                ("input_quality_grade", models.CharField(max_length=10)),
                (
                    "processing_type",
                    models.CharField(
                        choices=[
                            ("oil_extraction", "Oil Extraction"),
                            ("refining", "Refining"),
                            ("packaging", "Packaging"),
                            ("full_processing", "Full Processing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "expected_oil_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected oil output in liters/kg",
                        max_digits=12,
                    ),
                ),
                (
                    "expected_cake_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected oil cake output in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "actual_oil_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "actual_cake_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "oil_extraction_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("scheduled_start_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("expected_completion_date", models.DateField()),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "processing_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "additional_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("total_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "advance_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_queue", "In Queue"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "quality_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="processing/certificates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_orders",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_orders",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Order",
                "verbose_name_plural": "Processing Orders",
                "db_table": "processing_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_name", models.CharField(max_length=200)),
                (
                    "unit_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("oil_mill", "Oil Extraction Mill"),
                            ("solvent_extraction", "Solvent Extraction Plant"),
                            ("refinery", "Oil Refinery"),
                            ("packaging", "Packaging Unit"),
                            ("integrated", "Integrated Processing Unit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("fpo_owned", "FPO Owned"),
                            ("cooperative", "Cooperative"),
                            ("private", "Private"),
                            ("govt", "Government"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owner_name", models.CharField(max_length=200)),
                ("owner_contact", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("village", models.CharField(blank=True, max_length=100)),
                ("block", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("location", models.JSONField(blank=True, null=True)),
                (
                    "daily_capacity_quintals",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily processing capacity",
                        max_digits=10,
                    ),
                ),
                (
                    "annual_capacity_quintals",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual processing capacity",
                        max_digits=12,
                    ),
                ),
                (
                    "current_utilization_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("number_of_expellers", models.IntegerField(default=0)),
                (
                    "storage_capacity_quintals",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("has_quality_testing_lab", models.BooleanField(default=False)),
                ("has_packaging_facility", models.BooleanField(default=False)),
                (
                    "technology_type",
                    models.CharField(
                        choices=[
                            ("traditional", "Traditional Ghani"),
                            ("mechanical", "Mechanical Expeller"),
                            ("solvent", "Solvent Extraction"),
                            ("cold_press", "Cold Press"),
                            ("supercritical", "Supercritical CO2"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("semi_automated", "Semi-Automated"),
                            ("fully_automated", "Fully Automated"),
                        ],
                        default="semi_automated",
                        max_length=20,
                    ),
                ),
                ("fssai_license", models.CharField(max_length=14)),
                ("iso_certified", models.BooleanField(default=False)),
                ("iso_certificate_number", models.CharField(blank=True, max_length=50)),
                ("agmark_certified", models.BooleanField(default=False)),
                ("organic_certified", models.BooleanField(default=False)),
                ("halal_certified", models.BooleanField(default=False)),
                ("factory_license_number", models.CharField(max_length=50)),
                ("pollution_clearance", models.CharField(blank=True, max_length=50)),
                (
                    "fire_safety_certificate",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "products_manufactured",
                    models.JSONField(
                        default=list,
                        help_text="List of products: ['crude oil', 'refined oil', 'oil cake', ...]",
                    ),
                ),
                (
                    "average_oil_extraction_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average oil recovery %",
                        max_digits=5,
                    ),
                ),
                (
                    "processing_charges_per_quintal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Processing charges in INR",
                        max_digits=8,
                    ),
                ),
                ("toll_processing_available", models.BooleanField(default=True)),
                ("manager_name", models.CharField(max_length=200)),
                ("manager_contact", models.CharField(max_length=10)),
                ("manager_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("is_operational", models.BooleanField(default=True)),
                (
                    "total_processed_quintals",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_monthly_processing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("established_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_units",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Unit",
                "verbose_name_plural": "Processing Units",
                "db_table": "processing_units",
            },
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("production_date", models.DateField()),
                ("manufacturing_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "input_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "input_batch_numbers",
                    models.JSONField(
                        default=list, help_text="Source batch numbers from warehouse"
                    ),
                ),
                (
                    "products_produced",
                    models.JSONField(
                        default=dict,
                        help_text="{'product_id': {'quantity': 100, 'unit': 'liter'}}",
                    ),
                ),
                (
                    "oil_quality_ffa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Free Fatty Acid %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "oil_quality_moisture",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "oil_quality_impurities",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quality_test_report",
                    models.FileField(
                        blank=True, null=True, upload_to="quality_reports/"
                    ),
                ),
                ("quality_approved", models.BooleanField(default=False)),
                ("traceability_code", models.CharField(max_length=100, unique=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_production", "In Production"),
                            ("quality_check", "Quality Check"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("released", "Released to Market"),
                        ],
                        default="in_production",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "input_crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "processing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="processing.processingorder",
                    ),
                ),
                (
                    "processing_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing.processingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Batch",
                "verbose_name_plural": "Production Batches",
                "db_table": "production_batches",
                "ordering": ["-production_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("crude_oil", "Crude Oil"),
                            ("refined_oil", "Refined Oil"),
                            ("filtered_oil", "Filtered Oil"),
                            ("oil_cake", "Oil Cake"),
                            ("packaged_oil", "Packaged Oil"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(default=dict, help_text="Product specifications"),
                ),
                (
                    "packaging_unit",
                    models.CharField(
                        choices=[
                            ("liter", "Liter"),
                            ("kg", "Kilogram"),
                            ("quintal", "Quintal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "available_pack_sizes",
                    models.JSONField(
                        default=list, help_text="['1L', '5L', '15L', '1kg', '50kg']"
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=100)),
                ("has_agmark", models.BooleanField(default=False)),
                ("has_fssai", models.BooleanField(default=True)),
                ("is_organic", models.BooleanField(default=False)),
                ("certifications", models.JSONField(default=list)),
                (
                    "base_price_per_unit",
                    models.DecimalField(
                        decimal_places=2, help_text="Base price in INR", max_digits=10
                    ),
                ),
                (
                    "mrp_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum Retail Price",
                        max_digits=10,
                    ),
                ),
                ("shelf_life_months", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "fpo_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branded_products",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
            },
        ),
        migrations.AddField(
            model_name="processingorder",
            name="processing_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_orders",
                to="processing.processingunit",
            ),
        ),
        migrations.CreateModel(
            name="ByProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "byproduct_type",
                    models.CharField(
                        choices=[
                            ("oil_cake", "Oil Cake"),
                            ("meal", "Meal"),
                            ("husk", "Husk"),
                            ("shell", "Shell"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity in quintals/kg",
                        max_digits=12,
                    ),
                ),
                (
                    "protein_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For oil cake",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "market_price_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "quantity_sold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_sold", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="byproducts",
                        to="processing.processingorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "By-Product",
                "verbose_name_plural": "By-Products",
                "db_table": "byproducts",
            },
        ),
        migrations.CreateModel(
            name="ValueAddition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "total_input_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total raw material processed",
                        max_digits=12,
                    ),
                ),
                (
                    "total_input_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total input cost in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "total_output_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_output_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total output value in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "processing_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "packaging_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labour_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_processing_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "gross_value_addition",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "net_value_addition",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "value_addition_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("members_benefited", models.IntegerField()),
                (
                    "average_benefit_per_member",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_additions",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "processing_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing.processingunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Value Addition",
                "verbose_name_plural": "Value Additions",
                "db_table": "value_additions",
                "unique_together": {("fpo", "processing_unit", "month", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="processingunit",
            index=models.Index(
                fields=["unit_code"], name="processing__unit_co_1f4d35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingunit",
            index=models.Index(
                fields=["district", "state"], name="processing__distric_2a15a4_idx"
            ),
        ),
    ]
