# Generated by Django 4.2.26 on 2025-12-01 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fpos", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "farmer_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "total_land_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Total land in acres", max_digits=10
                    ),
                ),
                (
                    "irrigated_land",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Irrigated land in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "rain_fed_land",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rain-fed land in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "farmer_category",
                    models.CharField(
                        choices=[
                            ("marginal", "Marginal (< 1 hectare)"),
                            ("small", "Small (1-2 hectares)"),
                            ("semi_medium", "Semi-Medium (2-4 hectares)"),
                            ("medium", "Medium (4-10 hectares)"),
                            ("large", "Large (> 10 hectares)"),
                        ],
                        default="marginal",
                        max_length=20,
                    ),
                ),
                (
                    "caste_category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("obc", "OBC"),
                            ("sc", "SC"),
                            ("st", "ST"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("is_fpo_member", models.BooleanField(default=False)),
                ("has_kisan_credit_card", models.BooleanField(default=False)),
                ("kcc_number", models.CharField(blank=True, max_length=20)),
                ("has_pmfby_insurance", models.BooleanField(default=False)),
                ("pmfby_policy_number", models.CharField(blank=True, max_length=30)),
                ("has_pm_kisan", models.BooleanField(default=False)),
                (
                    "total_production",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total production in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "average_yield",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average yield per acre",
                        max_digits=8,
                    ),
                ),
                ("credit_score", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_members",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
                "db_table": "farmers",
                "indexes": [
                    models.Index(
                        fields=["farmer_id"], name="farmers_farmer__94501b_idx"
                    ),
                    models.Index(
                        fields=["is_fpo_member"], name="farmers_is_fpo__417046_idx"
                    ),
                ],
            },
        ),
    ]
