# Generated by Django 4.2.26 on 2025-11-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crops", "0001_initial"),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "farmer_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "total_land_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Total land in acres", max_digits=10
                    ),
                ),
                (
                    "irrigated_land",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Irrigated land in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "rain_fed_land",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rain-fed land in acres",
                        max_digits=10,
                    ),
                ),
                (
                    "farmer_category",
                    models.CharField(
                        choices=[
                            ("marginal", "Marginal (< 1 hectare)"),
                            ("small", "Small (1-2 hectares)"),
                            ("semi_medium", "Semi-Medium (2-4 hectares)"),
                            ("medium", "Medium (4-10 hectares)"),
                            ("large", "Large (> 10 hectares)"),
                        ],
                        default="marginal",
                        max_length=20,
                    ),
                ),
                (
                    "caste_category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("obc", "OBC"),
                            ("sc", "SC"),
                            ("st", "ST"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("is_fpo_member", models.BooleanField(default=False)),
                ("has_kisan_credit_card", models.BooleanField(default=False)),
                ("kcc_number", models.CharField(blank=True, max_length=20)),
                ("has_pmfby_insurance", models.BooleanField(default=False)),
                ("pmfby_policy_number", models.CharField(blank=True, max_length=30)),
                ("has_pm_kisan", models.BooleanField(default=False)),
                (
                    "total_production",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total production in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "average_yield",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average yield per acre",
                        max_digits=8,
                    ),
                ),
                ("credit_score", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_members",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer",
                "verbose_name_plural": "Farmers",
                "db_table": "farmers",
            },
        ),
        migrations.CreateModel(
            name="FarmPlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plot_name", models.CharField(max_length=100)),
                (
                    "survey_number",
                    models.CharField(help_text="Survey/Khasra number", max_length=50),
                ),
                ("sub_division", models.CharField(blank=True, max_length=50)),
                ("village", models.CharField(max_length=100)),
                ("taluka", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("boundary", models.JSONField(blank=True, null=True)),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, help_text="Area in acres", max_digits=10
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("alluvial", "Alluvial"),
                            ("black", "Black (Regur)"),
                            ("red", "Red"),
                            ("laterite", "Laterite"),
                            ("sandy", "Sandy"),
                            ("clay", "Clay"),
                            ("loamy", "Loamy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("canal", "Canal"),
                            ("borewell", "Borewell"),
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("rain_fed", "Rain-fed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "organic_carbon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("soil_health_card_date", models.DateField(blank=True, null=True)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("leased", "Leased"),
                            ("shared", "Shared"),
                        ],
                        default="owned",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_plots",
                        to="farmers.farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Plot",
                "verbose_name_plural": "Farm Plots",
                "db_table": "farm_plots",
            },
        ),
        migrations.CreateModel(
            name="CropPlanning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif (Monsoon)"),
                            ("rabi", "Rabi (Winter)"),
                            ("zaid", "Zaid (Summer)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "area_planned",
                    models.DecimalField(
                        decimal_places=2, help_text="Area in acres", max_digits=10
                    ),
                ),
                ("planned_sowing_date", models.DateField()),
                ("actual_sowing_date", models.DateField(blank=True, null=True)),
                ("expected_harvest_date", models.DateField()),
                ("actual_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "expected_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected yield in quintals",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual yield in quintals",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "input_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total input cost in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue in INR",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("sowing", "Sowing"),
                            ("growing", "Growing"),
                            ("harvesting", "Harvesting"),
                            ("harvested", "Harvested"),
                            ("sold", "Sold"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("committed_to_fpo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farm_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_plans",
                        to="farmers.farmplot",
                    ),
                ),
                (
                    "fpo_commitment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crop_commitments",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crops.cropvariety",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Planning",
                "verbose_name_plural": "Crop Planning",
                "db_table": "crop_planning",
            },
        ),
        migrations.CreateModel(
            name="FPOMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_number", models.CharField(max_length=20, unique=True)),
                ("joining_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("shares_held", models.IntegerField(default=1)),
                (
                    "share_value_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_share_capital",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("has_voting_rights", models.BooleanField(default=True)),
                (
                    "total_produce_supplied",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total produce supplied in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total earnings from FPO in INR",
                        max_digits=15,
                    ),
                ),
                (
                    "dividend_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total dividend earned in INR",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_memberships",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Membership",
                "verbose_name_plural": "FPO Memberships",
                "db_table": "fpo_memberships",
                "unique_together": {("farmer", "fpo")},
            },
        ),
        migrations.AddIndex(
            model_name="farmplot",
            index=models.Index(
                fields=["survey_number"], name="farm_plots_survey__a603d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmplot",
            index=models.Index(
                fields=["district", "state"], name="farm_plots_distric_a8b21d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(fields=["farmer_id"], name="farmers_farmer__94501b_idx"),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["is_fpo_member"], name="farmers_is_fpo__417046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cropplanning",
            index=models.Index(
                fields=["season", "year"], name="crop_planni_season_147910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cropplanning",
            index=models.Index(fields=["status"], name="crop_planni_status_2c8700_idx"),
        ),
    ]
