# Generated by Django 4.2.23 on 2025-12-04 19:19

import apps.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], max_length=50)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (खरीफ) - June to October'), ('rabi', 'Rabi (रबी) - November to March'), ('zaid', 'Zaid (जायद) - March to June')], max_length=20)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('cultivation_area_acres', models.DecimalField(decimal_places=2, max_digits=8, validators=[apps.core.validators.validate_positive])),
                ('expected_yield_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_variety', models.CharField(blank=True, max_length=100)),
                ('seed_quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fertilizer_used', models.JSONField(default=list, help_text='List of fertilizers used')),
                ('pesticide_used', models.JSONField(default=list, help_text='List of pesticides used')),
                ('organic_farming', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('sowed', 'Sowed'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('sold', 'Sold')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Crop Planning',
                'verbose_name_plural': 'Crop Planning',
                'db_table': 'crop_planning',
                'ordering': ['-sowing_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='farmers/profiles/')),
                ('total_land_acres', models.DecimalField(decimal_places=2, help_text='Total farmland in acres', max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('farming_experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ('primary_crops', models.JSONField(default=list, help_text="List of primary crops grown. e.g., ['soybean', 'mustard']")),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.core.validators.validate_aadhaar])),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[apps.core.validators.validate_pan])),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('kyc_documents', models.JSONField(default=dict, help_text='URLs to uploaded KYC documents')),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=200)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, validators=[apps.core.validators.validate_ifsc])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('post_office', models.CharField(blank=True, max_length=100)),
                ('tehsil', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('pincode', models.CharField(max_length=6, validators=[apps.core.validators.validate_pincode])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_lots_created', models.IntegerField(default=0)),
                ('total_quantity_sold_quintals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='hi', max_length=10)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
                'db_table': 'farmer_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmLand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('land_name', models.CharField(help_text='Name or identifier for this land parcel', max_length=100)),
                ('land_area_acres', models.DecimalField(decimal_places=2, max_digits=8, validators=[apps.core.validators.validate_positive])),
                ('survey_number', models.CharField(blank=True, help_text='Government survey/khasra number', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay Soil'), ('sandy', 'Sandy Soil'), ('loamy', 'Loamy Soil'), ('black', 'Black Soil'), ('red', 'Red Soil'), ('alluvial', 'Alluvial Soil')], max_length=20)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('irrigation_available', models.BooleanField(default=False)),
                ('irrigation_type', models.CharField(blank=True, choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('canal', 'Canal'), ('well', 'Well/Tubewell'), ('rainfed', 'Rainfed')], max_length=50)),
                ('water_source', models.CharField(blank=True, choices=[('groundwater', 'Groundwater'), ('surface_water', 'Surface Water'), ('rainwater', 'Rainwater'), ('mixed', 'Mixed')], max_length=50)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('shared', 'Shared Cropping')], default='owned', max_length=20)),
                ('ownership_document', models.FileField(blank=True, null=True, upload_to='farmers/land_documents/')),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_lands', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Farm Land',
                'verbose_name_plural': 'Farm Lands',
                'db_table': 'farm_lands',
                'ordering': ['-created_at'],
            },
        ),
    ]
