# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='fpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_members', to='fpos.fpoprofile'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropplanning',
            name='farm_land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmers.farmland'),
        ),
        migrations.AddField(
            model_name='cropplanning',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmers.farmerprofile'),
        ),
    ]
