# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropplanning',
            name='farm_land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmers.farmland'),
        ),
        migrations.AddField(
            model_name='cropplanning',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='farmers.farmerprofile'),
        ),
    ]
