# Generated by Django 4.2.27 on 2025-12-08 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_initial'),
        ('farmers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('crop_type', models.CharField(choices=[('soybean', 'Soybean (सोयाबीन)'), ('mustard', 'Mustard (सरसों)'), ('groundnut', 'Groundnut (मूंगफली)'), ('sunflower', 'Sunflower (सूरजमुखी)'), ('safflower', 'Safflower (कुसुम)'), ('sesame', 'Sesame (तिल)'), ('linseed', 'Linseed (अलसी)'), ('niger', 'Niger (रामतिल)')], help_text='Type of oilseed crop', max_length=50)),
                ('crop_name', models.CharField(help_text="Display name of crop (e.g., 'Soybean', 'Groundnut')", max_length=100)),
                ('land_acres', models.DecimalField(decimal_places=2, help_text='Land allocated in acres', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sowing_date', models.DateField(help_text='Date of sowing/planting')),
                ('maturity_days', models.IntegerField(help_text='Number of days to maturity', validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_harvest_date', models.DateField(help_text='Auto-calculated harvest date')),
                ('season', models.CharField(choices=[('kharif', 'Kharif (खरीफ) - June to October'), ('rabi', 'Rabi (रबी) - November to March'), ('zaid', 'Zaid (जायद) - March to June')], help_text='Cultivation season', max_length=20)),
                ('msp_price_per_quintal', models.DecimalField(decimal_places=2, help_text='MSP price per quintal in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_yield_quintals', models.DecimalField(decimal_places=2, help_text='Total estimated yield in quintals', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_yield_per_acre', models.DecimalField(decimal_places=2, help_text='Estimated yield per acre in quintals', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Gross revenue = estimated_yield × MSP', max_digits=12)),
                ('seed_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of seeds in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of fertilizers in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pesticide_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost of pesticides in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Labor cost in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('irrigation_cost', models.DecimalField(decimal_places=2, default=0, help_text='Irrigation cost in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_input_costs', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all input costs', max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, help_text='Net profit = gross_revenue - total_input_costs', max_digits=12)),
                ('profit_per_acre', models.DecimalField(decimal_places=2, default=0, help_text='Net profit per acre', max_digits=10)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, help_text='ROI = (net_profit / total_input_costs) × 100', max_digits=6)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('sowing', 'Sowing'), ('growing', 'Growing'), ('ready_to_harvest', 'Ready to Harvest'), ('harvested', 'Harvested'), ('converted_to_lot', 'Converted to Lot')], default='planned', help_text='Current status of crop plan', max_length=20)),
                ('actual_yield_quintals', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield after harvest (filled post-harvest)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('conversion_date', models.DateTimeField(blank=True, help_text='Date when plan was converted to lot', null=True)),
                ('converted_lot', models.ForeignKey(blank=True, help_text='Procurement lot created from this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_crop_plan', to='lots.procurementlot')),
                ('farm_land', models.ForeignKey(blank=True, help_text='Optional: Link to specific farm land parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simplified_crop_plans', to='farmers.farmland')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_crop_plans', to='farmers.farmerprofile')),
            ],
            options={
                'verbose_name': 'Crop Plan',
                'verbose_name_plural': 'Crop Plans',
                'db_table': 'crop_plans',
                'ordering': ['-created_at', '-sowing_date'],
                'indexes': [models.Index(fields=['farmer', 'status'], name='crop_plans_farmer__782cc8_idx'), models.Index(fields=['sowing_date'], name='crop_plans_sowing__5494b9_idx'), models.Index(fields=['crop_type', 'season'], name='crop_plans_crop_ty_1d6aac_idx')],
            },
        ),
    ]
