# Generated by Django 4.2.27 on 2025-12-08 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_cropplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='estimated_yield_quintals',
            field=models.DecimalField(decimal_places=2, help_text='Total estimated yield in quintals', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
