# Generated by Django 4.2.27 on 2025-12-09 07:30

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_cropplan_estimated_yield_quintals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[apps.core.validators.validate_pincode]),
        ),
    ]
