# Generated by Django 4.2.26 on 2025-12-01 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "processor_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "business_scale",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("fssai_license", models.CharField(max_length=14)),
                (
                    "monthly_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Processing capacity (quintals/month)",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_requirement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Raw material needed (quintals/month)",
                        max_digits=10,
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[6-9]\\d{9}$")
                        ],
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processors",
                "indexes": [
                    models.Index(
                        fields=["processor_code"], name="processors_process_d56d41_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="processors_city_cccef5_idx"
                    ),
                    models.Index(
                        fields=["is_verified", "is_active"],
                        name="processors_is_veri_6a9b2b_idx",
                    ),
                ],
            },
        ),
    ]
