# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('crude_oil', 'Crude Oil'), ('refined_oil', 'Refined Oil'), ('oil_cake', 'Oil Cake'), ('hulls', 'Hulls/Shells')], max_length=50)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_quantity_quintals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_location', models.CharField(max_length=200)),
                ('storage_conditions', models.CharField(choices=[('ambient', 'Ambient Temperature'), ('cool_dry', 'Cool & Dry'), ('refrigerated', 'Refrigerated'), ('climate_controlled', 'Climate Controlled')], default='cool_dry', max_length=50)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('quality_test_report', models.FileField(blank=True, null=True, upload_to='quality_reports/')),
                ('packaging_type', models.CharField(blank=True, max_length=100)),
                ('units_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_packages', models.IntegerField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('expired', 'Expired')], default='in_stock', max_length=20)),
                ('cost_per_quintal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price_per_quintal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'finished_products',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('initial_quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaned_quantity_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dehulled_quantity_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crushed_quantity_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conditioned_quantity_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oil_extracted_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refined_oil_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cake_produced_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hulls_produced_quintals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waste_quantity_quintals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processing_method', models.CharField(choices=[('cold_pressed', 'Cold Pressed'), ('hot_pressed', 'Hot Pressed'), ('solvent_extraction', 'Solvent Extraction'), ('expeller_pressed', 'Expeller Pressed')], default='cold_pressed', max_length=50)),
                ('current_stage', models.CharField(choices=[('cleaning', 'Cleaning'), ('dehulling', 'Dehulling'), ('crushing', 'Crushing'), ('conditioning', 'Conditioning'), ('pressing', 'Pressing'), ('filtration', 'Filtration'), ('refining', 'Refining'), ('packaging', 'Packaging')], default='cleaning', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'processing_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plant_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50)),
                ('capacity_quintals_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'processing_plants',
            },
        ),
        migrations.CreateModel(
            name='ProcessingStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.CharField(choices=[('cleaning', 'Cleaning'), ('dehulling', 'Dehulling'), ('crushing', 'Crushing'), ('conditioning', 'Conditioning'), ('pressing', 'Pressing'), ('filtration', 'Filtration'), ('refining', 'Refining'), ('packaging', 'Packaging')], max_length=50)),
                ('input_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_metrics', models.JSONField(blank=True, help_text='Store quality parameters like moisture %, purity %, etc.', null=True)),
                ('equipment_used', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('issues_encountered', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'processing_stage_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50)),
                ('processing_capacity_quintals_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'processor_profiles',
            },
        ),
    ]
