# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('processing_capacity_quintals_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processor_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProcessingPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plant_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('capacity_quintals_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='processors.processorprofile')),
            ],
            options={
                'db_table': 'processing_plants',
            },
        ),
        migrations.CreateModel(
            name='ProcessingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('processed_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oil_extracted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cake_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_date', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_batches', to='lots.procurementlot')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='processors.processingplant')),
            ],
            options={
                'db_table': 'processing_batches',
            },
        ),
    ]
