# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingstagelog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='processors.processingbatch'),
        ),
        migrations.AddField(
            model_name='processingstagelog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processingplant',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='processors.processorprofile'),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_batches', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='processors.processingplant'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='processors.processingbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='processingstagelog',
            unique_together={('batch', 'stage')},
        ),
    ]
