# Generated by Django 4.2.7 on 2025-12-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processors', '0002_alter_processingplant_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingbatch',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='processingbatch',
            name='cake_produced',
        ),
        migrations.RemoveField(
            model_name='processingbatch',
            name='oil_extracted',
        ),
        migrations.RemoveField(
            model_name='processingbatch',
            name='processed_quantity',
        ),
        migrations.RemoveField(
            model_name='processingbatch',
            name='processing_date',
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='cake_produced_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='cleaned_quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='conditioned_quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='crushed_quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='current_stage',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('dehulling', 'Dehulling'), ('crushing', 'Crushing'), ('conditioning', 'Conditioning'), ('pressing', 'Pressing'), ('filtration', 'Filtration'), ('refining', 'Refining'), ('packaging', 'Packaging')], default='cleaning', max_length=50),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='dehulled_quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='hulls_produced_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='initial_quantity_quintals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='oil_extracted_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='processing_method',
            field=models.CharField(choices=[('cold_pressed', 'Cold Pressed'), ('hot_pressed', 'Hot Pressed'), ('solvent_extraction', 'Solvent Extraction'), ('expeller_pressed', 'Expeller Pressed')], default='cold_pressed', max_length=50),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='refined_oil_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='waste_quantity_quintals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('crude_oil', 'Crude Oil'), ('refined_oil', 'Refined Oil'), ('oil_cake', 'Oil Cake'), ('hulls', 'Hulls/Shells')], max_length=50)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_quantity_quintals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_location', models.CharField(max_length=200)),
                ('storage_conditions', models.CharField(choices=[('ambient', 'Ambient Temperature'), ('cool_dry', 'Cool & Dry'), ('refrigerated', 'Refrigerated'), ('climate_controlled', 'Climate Controlled')], default='cool_dry', max_length=50)),
                ('quality_grade', models.CharField(blank=True, max_length=50)),
                ('quality_test_report', models.FileField(blank=True, null=True, upload_to='quality_reports/')),
                ('packaging_type', models.CharField(blank=True, max_length=100)),
                ('units_per_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_packages', models.IntegerField(blank=True, null=True)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('expired', 'Expired')], default='in_stock', max_length=20)),
                ('cost_per_quintal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price_per_quintal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='processors.processingbatch')),
            ],
            options={
                'db_table': 'finished_products',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stage', models.CharField(choices=[('cleaning', 'Cleaning'), ('dehulling', 'Dehulling'), ('crushing', 'Crushing'), ('conditioning', 'Conditioning'), ('pressing', 'Pressing'), ('filtration', 'Filtration'), ('refining', 'Refining'), ('packaging', 'Packaging')], max_length=50)),
                ('input_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quality_metrics', models.JSONField(blank=True, help_text='Store quality parameters like moisture %, purity %, etc.', null=True)),
                ('equipment_used', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('issues_encountered', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='processors.processingbatch')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing_stage_logs',
                'ordering': ['created_at'],
                'unique_together': {('batch', 'stage')},
            },
        ),
    ]
