# Generated by Django 4.2.27 on 2025-12-08 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('soybean_oil', 'Soybean Oil'), ('mustard_oil', 'Mustard Oil'), ('groundnut_oil', 'Groundnut Oil'), ('sunflower_oil', 'Sunflower Oil'), ('sesame_oil', 'Sesame Oil'), ('safflower_oil', 'Safflower Oil'), ('linseed_oil', 'Linseed Oil'), ('cottonseed_oil', 'Cottonseed Oil'), ('ricebran_oil', 'Rice Bran Oil'), ('palm_oil', 'Palm Oil')], max_length=50)),
                ('processing_type', models.CharField(choices=[('cold_pressed', 'Cold Pressed'), ('hot_pressed', 'Hot Pressed'), ('refined', 'Refined'), ('filtered', 'Filtered'), ('virgin', 'Virgin'), ('extra_virgin', 'Extra Virgin')], max_length=50)),
                ('batch_number', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_quantity_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_quantity_liters', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], max_length=50)),
                ('fssai_license', models.CharField(blank=True, max_length=100)),
                ('quality_certificate', models.FileField(blank=True, null=True, upload_to='quality_certificates/')),
                ('lab_test_report', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('packaging_type', models.CharField(choices=[('bulk_tanker', 'Bulk Tanker'), ('ibc_1000l', 'IBC Container (1000L)'), ('drum_200l', 'Drum (200L)'), ('jerry_can_20l', 'Jerry Can (20L)'), ('bottle_5l', 'Bottle (5L)'), ('bottle_1l', 'Bottle (1L)')], max_length=50)),
                ('packaging_date', models.DateField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('cost_price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available_for_sale', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('storage_location', models.CharField(max_length=200)),
                ('storage_temperature', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil_products', to='processors.processingbatch')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_products', to='processors.processorprofile')),
            ],
            options={
                'db_table': 'processed_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type', 'is_available_for_sale'], name='processed_p_product_bd9f22_idx'), models.Index(fields=['processor', 'is_available_for_sale'], name='processed_p_process_ae004a_idx')],
            },
        ),
    ]
