# Generated by Django 4.2.27 on 2025-12-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0003_processedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='oil_type',
            field=models.CharField(blank=True, help_text='Type of oil (Soybean, Mustard, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='processors.processorprofile'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='quantity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For oil products', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='processing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='processing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='quality_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='processingbatch',
            name='yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='available_quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='quantity_quintals',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For cake/hulls', max_digits=10, null=True),
        ),
    ]
