# Generated by Django 4.2.27 on 2025-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processors', '0004_finishedproduct_oil_type_finishedproduct_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Processor location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='processorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Processor location longitude', max_digits=9, null=True),
        ),
    ]
