# Generated by Django 4.2.26 on 2025-11-29 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "advisory_type",
                    models.CharField(
                        choices=[
                            ("weather", "Weather Advisory"),
                            ("pest", "Pest Management"),
                            ("disease", "Disease Management"),
                            ("irrigation", "Irrigation Advisory"),
                            ("fertilizer", "Fertilizer Advisory"),
                            ("harvest", "Harvest Advisory"),
                            ("market", "Market Advisory"),
                            ("general", "General Advisory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("content_hindi", models.TextField(blank=True)),
                (
                    "content_regional",
                    models.JSONField(
                        default=dict, help_text="Regional language translations"
                    ),
                ),
                ("target_states", models.JSONField(blank=True, default=list)),
                ("target_districts", models.JSONField(blank=True, default=list)),
                ("valid_from", models.DateTimeField()),
                ("valid_till", models.DateTimeField()),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI model confidence (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="advisories/"),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="advisories/audio/"
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_advisories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisories",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisory",
                "verbose_name_plural": "Advisories",
                "db_table": "advisories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("price_forecast", "Price Forecasting"),
                            ("yield_prediction", "Yield Prediction"),
                            ("pest_detection", "Pest Detection"),
                            ("disease_detection", "Disease Detection"),
                            ("soil_analysis", "Soil Health Analysis"),
                            ("weather_prediction", "Weather Prediction"),
                            ("credit_scoring", "Credit Scoring"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                (
                    "algorithm",
                    models.CharField(
                        help_text="e.g., Random Forest, LSTM, CNN", max_length=100
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        help_text="e.g., TensorFlow, PyTorch, scikit-learn",
                        max_length=50,
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "recall",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "training_data_size",
                    models.IntegerField(help_text="Number of training samples"),
                ),
                ("training_date", models.DateField()),
                ("last_retrained", models.DateField(blank=True, null=True)),
                ("model_file_path", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("is_production", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                (
                    "districts",
                    models.JSONField(default=list, help_text="Affected districts"),
                ),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("affected_area", models.JSONField(blank=True, null=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("rainfall", "Heavy Rainfall"),
                            ("drought", "Drought Warning"),
                            ("heatwave", "Heat Wave"),
                            ("frost", "Frost Warning"),
                            ("cyclone", "Cyclone Alert"),
                            ("hailstorm", "Hailstorm Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow (Be Aware)"),
                            ("orange", "Orange (Be Prepared)"),
                            ("red", "Red (Take Action)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "action_required",
                    models.TextField(help_text="Recommended actions for farmers"),
                ),
                (
                    "expected_rainfall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected rainfall in mm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Wind speed in km/h",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("alert_start", models.DateTimeField()),
                ("alert_end", models.DateTimeField()),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("imd", "IMD (India Meteorological Department)"),
                            ("skymet", "Skymet"),
                            ("openweather", "OpenWeatherMap"),
                        ],
                        default="imd",
                        max_length=50,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("farmers_notified", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weather Alert",
                "verbose_name_plural": "Weather Alerts",
                "db_table": "weather_alerts",
                "ordering": ["-alert_start"],
                "indexes": [
                    models.Index(fields=["state"], name="weather_ale_state_664eb5_idx"),
                    models.Index(
                        fields=["alert_start", "alert_end"],
                        name="weather_ale_alert_s_5a1f09_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="weather_ale_severit_e19b58_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SoilAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_date", models.DateField()),
                ("lab_name", models.CharField(max_length=200)),
                ("lab_reference_number", models.CharField(max_length=50, unique=True)),
                ("ph_value", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "electrical_conductivity",
                    models.DecimalField(
                        decimal_places=2, help_text="EC in dS/m", max_digits=6
                    ),
                ),
                (
                    "organic_carbon",
                    models.DecimalField(
                        decimal_places=2, help_text="Organic carbon %", max_digits=5
                    ),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        decimal_places=2, help_text="N in kg/ha", max_digits=6
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        decimal_places=2, help_text="P in kg/ha", max_digits=6
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        decimal_places=2, help_text="K in kg/ha", max_digits=6
                    ),
                ),
                (
                    "sulphur",
                    models.DecimalField(
                        decimal_places=2, help_text="S in ppm", max_digits=6
                    ),
                ),
                (
                    "zinc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Zn in ppm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "iron",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fe in ppm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "manganese",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mn in ppm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "copper",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cu in ppm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "boron",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="B in ppm",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("fertilizer_recommendation", models.TextField()),
                ("lime_gypsum_recommendation", models.TextField(blank=True)),
                ("organic_manure_recommendation", models.TextField()),
                ("ai_recommendation", models.TextField(blank=True)),
                (
                    "soil_health_score",
                    models.IntegerField(
                        default=0, help_text="Overall soil health score (0-100)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_analyses",
                        to="farmers.farmplot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Analysis",
                "verbose_name_plural": "Soil Analyses",
                "db_table": "soil_analyses",
                "ordering": ["-sample_date"],
            },
        ),
        migrations.CreateModel(
            name="PestDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="pest_detection/")),
                (
                    "detection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Analysis"),
                            ("detected", "Pest/Disease Detected"),
                            ("not_detected", "No Pest/Disease"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("detected_pest_disease", models.CharField(blank=True, max_length=200)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("treatment_recommended", models.TextField(blank=True)),
                (
                    "pesticide_recommended",
                    models.JSONField(
                        default=list, help_text="List of recommended pesticides"
                    ),
                ),
                ("organic_treatment", models.TextField(blank=True)),
                ("expert_validated", models.BooleanField(default=False)),
                ("expert_comments", models.TextField(blank=True)),
                ("treatment_applied", models.BooleanField(default=False)),
                ("treatment_effective", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farm_plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_detections",
                        to="farmers.farmplot",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_detections",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest Detection",
                "verbose_name_plural": "Pest Detections",
                "db_table": "pest_detections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FPOAdvisory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_message", models.TextField(blank=True)),
                (
                    "priority_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_member_count", models.IntegerField(default=0)),
                ("notified_member_count", models.IntegerField(default=0)),
                ("members_acknowledged", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fpo_advisories",
                        to="advisories.advisory",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisories",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Advisory",
                "verbose_name_plural": "FPO Advisories",
                "db_table": "fpo_advisories",
            },
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(
                fields=["advisory_type"], name="advisories_advisor_5d6c14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(
                fields=["valid_from", "valid_till"],
                name="advisories_valid_f_85ef4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=models.Index(
                fields=["is_published", "is_active"],
                name="advisories_is_publ_bff890_idx",
            ),
        ),
    ]
