# Generated by Django 4.2.26 on 2025-11-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("model_code", models.CharField(max_length=50, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("production", "Production Forecast"),
                            ("price", "Price Forecast"),
                            ("demand", "Demand Forecast"),
                            ("import", "Import Requirement Forecast"),
                            ("area", "Area Coverage Forecast"),
                            ("yield", "Yield Forecast"),
                            ("revenue", "Revenue Forecast"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("arima", "ARIMA"),
                            ("sarima", "SARIMA"),
                            ("lstm", "LSTM Neural Network"),
                            ("prophet", "Facebook Prophet"),
                            ("random_forest", "Random Forest"),
                            ("gradient_boosting", "Gradient Boosting"),
                            ("ensemble", "Ensemble Method"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "input_features",
                    models.JSONField(
                        default=list, help_text="List of input features used"
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(default=dict, help_text="Model hyperparameters"),
                ),
                ("training_data_period_start", models.DateField()),
                ("training_data_period_end", models.DateField()),
                ("training_date", models.DateField()),
                ("training_samples", models.IntegerField()),
                (
                    "accuracy_score",
                    models.DecimalField(
                        decimal_places=2, help_text="Accuracy percentage", max_digits=5
                    ),
                ),
                (
                    "rmse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Root Mean Square Error",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "mae",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Mean Absolute Error",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "r2_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="R-squared score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "validation_method",
                    models.CharField(
                        choices=[
                            ("train_test_split", "Train-Test Split"),
                            ("cross_validation", "Cross Validation"),
                            ("time_series_cv", "Time Series CV"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "validation_accuracy",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "forecast_horizon_months",
                    models.IntegerField(
                        help_text="How many months ahead can this model predict"
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model_file_path",
                    models.CharField(
                        help_text="Path to saved model file", max_length=500
                    ),
                ),
                ("total_predictions", models.IntegerField(default=0)),
                ("average_prediction_time_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_models",
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Model",
                "verbose_name_plural": "Forecast Models",
                "db_table": "forecast_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("simulation_name", models.CharField(max_length=200)),
                ("simulation_code", models.CharField(max_length=50, unique=True)),
                (
                    "simulation_type",
                    models.CharField(
                        choices=[
                            ("subsidy", "Subsidy Impact"),
                            ("msp", "MSP Change Impact"),
                            ("infrastructure", "Infrastructure Investment"),
                            ("fpo_expansion", "FPO Expansion"),
                            ("technology", "Technology Adoption"),
                            ("price_support", "Price Support Mechanism"),
                            ("import_policy", "Import Policy Change"),
                            ("credit", "Credit Policy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("policy_description", models.TextField()),
                (
                    "intervention_details",
                    models.JSONField(
                        default=dict, help_text="Details of the policy intervention"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("simulation_period_years", models.IntegerField()),
                ("baseline_year", models.IntegerField()),
                (
                    "estimated_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated budget in INR Crores",
                        max_digits=15,
                    ),
                ),
                (
                    "baseline_metrics",
                    models.JSONField(
                        default=dict, help_text="Baseline values of key metrics"
                    ),
                ),
                (
                    "projected_metrics",
                    models.JSONField(
                        default=dict, help_text="Projected values after intervention"
                    ),
                ),
                (
                    "production_increase_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "farmer_income_increase_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "import_reduction_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("fpo_coverage_increase", models.IntegerField(blank=True, null=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_benefit", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "benefit_cost_ratio",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("roi_percentage", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estimated_beneficiaries", models.IntegerField()),
                (
                    "per_beneficiary_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("risks", models.JSONField(default=list)),
                ("mitigation_strategies", models.JSONField(default=list)),
                ("implementation_roadmap", models.TextField()),
                ("monitoring_indicators", models.JSONField(default=list)),
                ("simulation_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("approved", "Approved"),
                            ("implemented", "Being Implemented"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "detailed_report",
                    models.FileField(
                        blank=True, null=True, upload_to="simulations/reports/"
                    ),
                ),
                (
                    "presentation",
                    models.FileField(
                        blank=True, null=True, upload_to="simulations/presentations/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forecast_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policy_dashboard.forecastmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Result",
                "verbose_name_plural": "Simulation Results",
                "db_table": "simulation_results",
                "ordering": ["-simulation_date"],
            },
        ),
        migrations.CreateModel(
            name="PolicyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=200)),
                (
                    "metric_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "metric_category",
                    models.CharField(
                        choices=[
                            ("production", "Production Metrics"),
                            ("area", "Area Coverage Metrics"),
                            ("fpo", "FPO Performance Metrics"),
                            ("price", "Price Stability Metrics"),
                            ("import_export", "Trade Metrics"),
                            ("farmer_income", "Farmer Income Metrics"),
                            ("subsidy", "Subsidy Utilization"),
                            ("infrastructure", "Infrastructure Development"),
                            ("technology", "Technology Adoption"),
                            ("sustainability", "Sustainability Metrics"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                            ("block", "Block"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("block", models.CharField(blank=True, max_length=100)),
                ("financial_year", models.CharField(max_length=10)),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Q1 (Apr-Jun)"),
                            (2, "Q2 (Jul-Sep)"),
                            (3, "Q3 (Oct-Dec)"),
                            (4, "Q4 (Jan-Mar)"),
                        ],
                        null=True,
                    ),
                ),
                ("month", models.IntegerField(blank=True, null=True)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "unit",
                    models.CharField(help_text="Unit of measurement", max_length=50),
                ),
                (
                    "baseline_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target as per NMEO-OP or state plan",
                        max_digits=15,
                    ),
                ),
                (
                    "achievement_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "previous_period_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "percentage_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upward", "Upward"),
                            ("downward", "Downward"),
                            ("stable", "Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nmeo_op_aligned", models.BooleanField(default=True)),
                (
                    "nmeo_op_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("data_source", models.CharField(max_length=200)),
                (
                    "data_reliability_score",
                    models.IntegerField(
                        default=100, help_text="Reliability score 0-100"
                    ),
                ),
                ("last_verified_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("behind", "Behind Target"),
                            ("critical", "Critical"),
                            ("achieved", "Target Achieved"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy Metric",
                "verbose_name_plural": "Policy Metrics",
                "db_table": "policy_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_category", "scope"],
                        name="policy_metr_metric__85e67b_idx",
                    ),
                    models.Index(
                        fields=["financial_year"], name="policy_metr_financi_ae584b_idx"
                    ),
                    models.Index(
                        fields=["status"], name="policy_metr_status_a96800_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "metric_code",
                        "scope",
                        "state",
                        "district",
                        "financial_year",
                        "quarter",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="DistrictPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("financial_year", models.CharField(max_length=10)),
                ("quarter", models.IntegerField()),
                (
                    "total_oilseed_production",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "production_target",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "production_achievement_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "area_under_oilseeds",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("area_target", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "area_achievement_percentage",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("number_of_fpos", models.IntegerField()),
                (
                    "fpo_coverage_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("farmers_in_fpos", models.IntegerField()),
                (
                    "average_farmer_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "income_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "overall_performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Composite score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "performance_grade",
                    models.CharField(
                        choices=[
                            ("A+", "Excellent (90-100)"),
                            ("A", "Very Good (80-89)"),
                            ("B", "Good (70-79)"),
                            ("C", "Average (60-69)"),
                            ("D", "Below Average (50-59)"),
                            ("F", "Poor (<50)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("state_rank", models.IntegerField()),
                ("national_rank", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "District Performance",
                "verbose_name_plural": "District Performances",
                "db_table": "district_performance",
                "unique_together": {("district", "state", "financial_year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommendation_code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=300)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("budget_allocation", "Budget Allocation"),
                            ("subsidy_revision", "Subsidy Revision"),
                            ("msp_adjustment", "MSP Adjustment"),
                            ("infrastructure", "Infrastructure Investment"),
                            ("fpo_support", "FPO Support Program"),
                            ("technology", "Technology Adoption"),
                            ("market_intervention", "Market Intervention"),
                            ("import_policy", "Import Policy"),
                            ("credit", "Credit Policy"),
                            ("risk_mitigation", "Risk Mitigation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "problem_statement",
                    models.TextField(help_text="What problem does this address?"),
                ),
                ("proposed_solution", models.TextField()),
                ("expected_outcomes", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgency_score",
                    models.IntegerField(default=50, help_text="Urgency score 0-100"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_budget_required",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budget required in INR Crores",
                        max_digits=15,
                    ),
                ),
                (
                    "expected_roi_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("payback_period_years", models.IntegerField(blank=True, null=True)),
                (
                    "implementation_timeframe",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate (0-3 months)"),
                            ("short_term", "Short-term (3-12 months)"),
                            ("medium_term", "Medium-term (1-3 years)"),
                            ("long_term", "Long-term (3+ years)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("implementing_agency", models.CharField(max_length=200)),
                ("required_approvals", models.JSONField(default=list)),
                (
                    "expected_production_increase",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected increase %",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "expected_income_increase",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected increase %",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("beneficiaries_count", models.IntegerField(blank=True, null=True)),
                (
                    "data_sources",
                    models.JSONField(
                        default=list,
                        help_text="Sources of data used for this recommendation",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Being Implemented"),
                            ("completed", "Implementation Completed"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                ("review_comments", models.TextField(blank=True)),
                (
                    "detailed_report",
                    models.FileField(
                        blank=True, null=True, upload_to="recommendations/reports/"
                    ),
                ),
                ("generated_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "generated_by_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policy_dashboard.forecastmodel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simulation_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="policy_dashboard.simulationresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
                "db_table": "recommendations",
                "ordering": ["-urgency_score", "-generated_date"],
                "indexes": [
                    models.Index(
                        fields=["priority", "status"],
                        name="recommendat_priorit_44547f_idx",
                    ),
                    models.Index(
                        fields=["recommendation_type"],
                        name="recommendat_recomme_a6aa95_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportDependencyAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField(blank=True, null=True)),
                (
                    "domestic_production",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Domestic production in tonnes",
                        max_digits=15,
                    ),
                ),
                (
                    "domestic_consumption",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("total_imports", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "import_value_inr",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "average_import_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "top_import_countries",
                    models.JSONField(
                        default=list, help_text="List of countries with import volumes"
                    ),
                ),
                (
                    "import_dependency_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="% of consumption met by imports",
                        max_digits=5,
                    ),
                ),
                (
                    "self_sufficiency_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "supply_demand_gap",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "projected_next_year_import",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("policy_recommendations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Dependency Analysis",
                "verbose_name_plural": "Import Dependency Analyses",
                "db_table": "import_dependency_analysis",
                "unique_together": {("crop", "year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="FPOHealthScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("financial_year", models.CharField(max_length=10)),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[(1, "Q1"), (2, "Q2"), (3, "Q3"), (4, "Q4")]
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall health score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent (80-100)"),
                            ("good", "Good (60-79)"),
                            ("average", "Average (40-59)"),
                            ("poor", "Poor (20-39)"),
                            ("critical", "Critical (0-19)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financial_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "revenue_growth_rate",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("profit_margin", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "debt_equity_ratio",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "working_capital_adequacy",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "operational_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "procurement_efficiency",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "storage_utilization",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "logistics_efficiency",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "processing_capacity_utilization",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "member_engagement_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "active_member_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "member_retention_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "average_member_income_increase",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "member_satisfaction_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "governance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("board_meeting_frequency", models.IntegerField()),
                ("agm_conducted_on_time", models.BooleanField()),
                ("audit_completed", models.BooleanField()),
                (
                    "compliance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "market_linkage_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("number_of_buyers", models.IntegerField()),
                (
                    "value_of_contracts",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "price_realization_vs_mandi",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("total_members", models.IntegerField()),
                ("active_members", models.IntegerField()),
                (
                    "total_turnover",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("net_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("share_capital", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reserves", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "previous_quarter_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "score_change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        max_length=20,
                    ),
                ),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("recommendations", models.TextField()),
                ("priority_interventions", models.JSONField(default=list)),
                ("state_rank", models.IntegerField(blank=True, null=True)),
                ("district_rank", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scores",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Health Score",
                "verbose_name_plural": "FPO Health Scores",
                "db_table": "fpo_health_scores",
                "ordering": ["-assessment_date"],
                "indexes": [
                    models.Index(
                        fields=["overall_score"], name="fpo_health__overall_be56ec_idx"
                    ),
                    models.Index(
                        fields=["health_status"], name="fpo_health__health__410752_idx"
                    ),
                ],
                "unique_together": {("fpo", "financial_year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_for_year", models.IntegerField()),
                ("forecast_for_quarter", models.IntegerField(blank=True, null=True)),
                ("forecast_for_month", models.IntegerField(blank=True, null=True)),
                (
                    "forecast_for_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("generated_date", models.DateField(auto_now_add=True)),
                (
                    "forecasted_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("unit", models.CharField(max_length=50)),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=95.0, max_digits=5),
                ),
                ("lower_bound", models.DecimalField(decimal_places=2, max_digits=15)),
                ("upper_bound", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "forecast_error",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "forecast_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "assumptions",
                    models.JSONField(
                        default=dict, help_text="Key assumptions made in forecast"
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=list, help_text="Identified risk factors"),
                ),
                (
                    "forecast_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="policy_dashboard.forecastmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Result",
                "verbose_name_plural": "Forecast Results",
                "db_table": "forecast_results",
                "ordering": ["-generated_date"],
                "unique_together": {
                    ("forecast_model", "forecast_for_year", "forecast_for_quarter")
                },
            },
        ),
    ]
