# Generated by Django 4.2.26 on 2025-11-26 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('marketplace', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTrackingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, help_text='km/h', max_digits=5, null=True)),
                ('battery_level', models.IntegerField(help_text='Percentage', null=True)),
                ('is_moving', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gps_tracking_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.JSONField()),
                ('destination', models.JSONField()),
                ('optimal_route', models.JSONField()),
                ('distance', models.DecimalField(decimal_places=2, help_text='In km', max_digits=8)),
                ('estimated_time', models.IntegerField(help_text='In minutes')),
                ('estimated_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traffic_conditions', models.CharField(blank=True, max_length=50)),
                ('weather_impact', models.CharField(blank=True, max_length=100)),
                ('algorithm_used', models.CharField(default='Dijkstra', max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'route_optimizations',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_id', models.CharField(max_length=50, unique=True)),
                ('origin_address', models.TextField()),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('destination_address', models.TextField()),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('scheduled_pickup', models.DateTimeField()),
                ('actual_pickup', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery', models.DateTimeField()),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned to Logistics'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('estimated_distance', models.DecimalField(decimal_places=2, help_text='In km', max_digits=8, null=True)),
                ('freight_charges', models.DecimalField(decimal_places=2, help_text='₹', max_digits=10)),
                ('pod_signature', models.ImageField(blank=True, null=True, upload_to='pod_signatures/')),
                ('pod_photo', models.ImageField(blank=True, null=True, upload_to='pod_photos/')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('FPO', 'FPO'), ('PROCESSOR', 'Processor'), ('LOGISTICS', 'Logistics Partner')], max_length=20)),
                ('owner_id', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRACTOR', 'Tractor-Trolley'), ('SMALL_TRUCK', 'Small Truck (< 5 MT)'), ('MEDIUM_TRUCK', 'Medium Truck (5-10 MT)'), ('LARGE_TRUCK', 'Large Truck (> 10 MT)'), ('TANKER', 'Tanker'), ('REFRIGERATED', 'Refrigerated Vehicle')], max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='In metric tonnes', max_digits=6)),
                ('has_gps', models.BooleanField(default=False)),
                ('gps_device_id', models.CharField(blank=True, max_length=100)),
                ('rc_number', models.CharField(max_length=50)),
                ('insurance_valid_till', models.DateField()),
                ('fitness_valid_till', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In Transit'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('FPO', 'FPO'), ('PROCESSOR', 'Processor'), ('RETAILER', 'Retailer'), ('LOGISTICS', 'Logistics Partner')], max_length=20)),
                ('owner_id', models.IntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('warehouse_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('warehouse_type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('SHARED', 'Shared/Co-operative')], max_length=20)),
                ('storage_type', models.CharField(choices=[('OPEN', 'Open Storage'), ('COVERED', 'Covered Warehouse'), ('COLD', 'Cold Storage'), ('SCIENTIFIC', 'Scientific Storage (Controlled Environment)')], max_length=20)),
                ('total_capacity', models.DecimalField(decimal_places=2, help_text='In metric tonnes', max_digits=10)),
                ('current_occupancy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_weighbridge', models.BooleanField(default=False)),
                ('has_quality_testing', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='WarehouseSensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='°C', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('is_temperature_alert', models.BooleanField(default=False)),
                ('is_humidity_alert', models.BooleanField(default=False)),
                ('is_pest_detected', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='logistics.warehouse')),
            ],
            options={
                'db_table': 'warehouse_sensor_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['owner_type', 'owner_id'], name='warehouses_owner_t_baede1_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['state', 'district'], name='warehouses_state_11cc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner_type', 'owner_id'], name='vehicles_owner_t_593ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_number'], name='vehicles_vehicle_07aa58_idx'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='logistics_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.logisticsprofile'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='gpstrackinglog',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='logistics.shipment'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_id'], name='shipments_shipmen_a7cf11_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_status_cda325_idx'),
        ),
    ]
