# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fpos", "0001_initial"),
        ("farmers", "__first__"),
        ("procurement", "0001_initial"),
        ("compliance", "0001_initial"),
        ("processing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouses", "0001_initial"),
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_contributed",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity in kg", max_digits=10
                    ),
                ),
                ("quality_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("contribution_date", models.DateField()),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "batch_contributions",
            },
        ),
        migrations.CreateModel(
            name="FPOBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique batch identifier (e.g., FPO-CROP-YYYYMMDD-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("batch_name", models.CharField(max_length=200)),
                ("total_contributing_farmers", models.IntegerField(default=0)),
                (
                    "source_farms",
                    models.JSONField(
                        default=list, help_text="List of farm IDs with GPS coordinates"
                    ),
                ),
                (
                    "total_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total quantity in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Available quantity in kg",
                        max_digits=12,
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=20)),
                (
                    "average_quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "Premium"),
                            ("A", "Grade A"),
                            ("B", "Grade B"),
                            ("C", "Grade C"),
                        ],
                        max_length=10,
                    ),
                ),
                ("harvest_start_date", models.DateField()),
                ("harvest_end_date", models.DateField()),
                (
                    "harvest_season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "processing_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Oil Extraction, Cleaning, Sorting",
                        max_length=50,
                    ),
                ),
                ("processing_date", models.DateField(blank=True, null=True)),
                ("storage_start_date", models.DateField(blank=True, null=True)),
                ("storage_end_date", models.DateField(blank=True, null=True)),
                ("packaging_date", models.DateField(blank=True, null=True)),
                ("package_type", models.CharField(blank=True, max_length=100)),
                ("packages_count", models.IntegerField(default=0)),
                (
                    "package_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight per package in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("organic_certified", models.BooleanField(default=False)),
                ("fair_trade_certified", models.BooleanField(default=False)),
                ("agmark_certified", models.BooleanField(default=False)),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of batch data",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("blockchain_registered", models.BooleanField(default=False)),
                (
                    "blockchain_registration_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "previous_block_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of previous batch in chain",
                        max_length=64,
                    ),
                ),
                ("qr_code_generated", models.BooleanField(default=False)),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blockchain/qr_codes/"
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True, help_text="Public URL for QR code verification"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Batch Created"),
                            ("procurement_complete", "Procurement Complete"),
                            ("quality_checked", "Quality Checked"),
                            ("stored", "In Storage"),
                            ("processing", "Under Processing"),
                            ("processed", "Processing Complete"),
                            ("packed", "Packed"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("sold", "Sold to End Customer"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                (
                    "buyer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("processor", "Processor"),
                            ("exporter", "Exporter"),
                            ("government", "Government Agency"),
                            ("consumer", "Direct Consumer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destination_city", models.CharField(blank=True, max_length=100)),
                ("destination_state", models.CharField(blank=True, max_length=100)),
                (
                    "water_usage_liters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "carbon_footprint_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("pesticide_used", models.BooleanField(default=False)),
                ("pesticide_details", models.TextField(blank=True)),
                ("traceability_verified", models.BooleanField(default=False)),
                (
                    "verification_count",
                    models.IntegerField(
                        default=0, help_text="Number of times QR code was scanned"
                    ),
                ),
                ("last_verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional batch metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="certified_batches",
                        to="compliance.certificate",
                    ),
                ),
                (
                    "contributing_farmers",
                    models.ManyToManyField(
                        related_name="contributed_batches",
                        through="blockchain.BatchContribution",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "crop_variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="crops.cropvariety",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_batches",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "processing_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_batches",
                        to="processing.processingunit",
                    ),
                ),
                (
                    "procurement_orders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Procurement orders that contributed to this batch",
                        related_name="blockchain_batches",
                        to="procurement.procurementorder",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_batches",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Batch",
                "verbose_name_plural": "FPO Batches",
                "db_table": "fpo_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique QR code identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("batch", "Batch QR Code"),
                            ("package", "Package QR Code"),
                            ("certificate", "Certificate QR Code"),
                            ("farmer", "Farmer Profile QR"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        help_text="Generated QR code image",
                        upload_to="blockchain/qr_codes/",
                    ),
                ),
                (
                    "qr_code_svg",
                    models.FileField(
                        blank=True,
                        help_text="SVG version for printing",
                        null=True,
                        upload_to="blockchain/qr_codes/svg/",
                    ),
                ),
                (
                    "public_verification_url",
                    models.URLField(help_text="Public URL that QR code points to"),
                ),
                (
                    "embedded_data",
                    models.JSONField(
                        default=dict, help_text="Data embedded in QR code"
                    ),
                ),
                ("display_title", models.CharField(max_length=200)),
                ("display_description", models.TextField(blank=True)),
                (
                    "print_size_mm",
                    models.IntegerField(
                        default=50, help_text="Recommended print size in mm"
                    ),
                ),
                ("dpi", models.IntegerField(default=300)),
                (
                    "scan_count",
                    models.IntegerField(default=0, help_text="Total number of scans"),
                ),
                ("unique_scan_count", models.IntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_locations",
                    models.JSONField(
                        default=list, help_text="List of locations where QR was scanned"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("encryption_key", models.CharField(blank=True, max_length=64)),
                ("requires_authentication", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="blockchain.fpobatch",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="compliance.certificate",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
                "db_table": "qr_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contract_name", models.CharField(max_length=200)),
                ("contract_code", models.CharField(max_length=50, unique=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("procurement", "Procurement Agreement"),
                            ("quality_assurance", "Quality Assurance"),
                            ("payment", "Payment Terms"),
                            ("delivery", "Delivery Terms"),
                            ("price_guarantee", "Price Guarantee"),
                            ("insurance", "Crop Insurance"),
                            ("certification", "Certification Validation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("counterparty_name", models.CharField(max_length=200)),
                (
                    "counterparty_type",
                    models.CharField(
                        choices=[
                            ("buyer", "Buyer"),
                            ("processor", "Processor"),
                            ("insurer", "Insurance Company"),
                            ("government", "Government Agency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("terms_and_conditions", models.TextField()),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Conditions that trigger contract execution",
                    ),
                ),
                (
                    "execution_actions",
                    models.JSONField(
                        default=dict,
                        help_text="Actions to execute when conditions are met",
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total contract value in INR",
                        max_digits=15,
                    ),
                ),
                ("payment_terms", models.TextField()),
                ("penalty_terms", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "contract_address",
                    models.CharField(
                        blank=True,
                        help_text="Smart contract address on blockchain",
                        max_length=100,
                    ),
                ),
                ("deployment_hash", models.CharField(blank=True, max_length=64)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("deployed", "Deployed"),
                            ("active", "Active"),
                            ("executed", "Executed"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "contract_code_snippet",
                    models.TextField(blank=True, help_text="Chaincode or pseudo-code"),
                ),
                ("creation_hash", models.CharField(blank=True, max_length=64)),
                ("modification_history", models.JSONField(default=list)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True, null=True, upload_to="blockchain/smart_contracts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_contracts",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Contract",
                "verbose_name_plural": "Smart Contracts",
                "db_table": "smart_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("batch_creation", "Batch Creation"),
                            ("quality_update", "Quality Update"),
                            ("transfer", "Ownership Transfer"),
                            ("processing", "Processing Event"),
                            ("delivery", "Delivery Confirmation"),
                            ("certification", "Certification"),
                            ("payment", "Payment Record"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 transaction hash",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "transaction_data",
                    models.JSONField(
                        default=dict, help_text="Complete transaction payload"
                    ),
                ),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("block_hash", models.CharField(blank=True, max_length=64)),
                (
                    "previous_transaction_hash",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "from_party",
                    models.CharField(help_text="Sender/Source", max_length=200),
                ),
                (
                    "to_party",
                    models.CharField(help_text="Receiver/Destination", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("channel_name", models.CharField(blank=True, max_length=100)),
                ("chaincode_name", models.CharField(blank=True, max_length=100)),
                ("endorsement_policy", models.TextField(blank=True)),
                ("signature", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "transaction_fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=10),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_transactions",
                        to="blockchain.fpobatch",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_transactions",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "smart_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="blockchain.smartcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain Transaction",
                "verbose_name_plural": "Blockchain Transactions",
                "db_table": "blockchain_transactions",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(max_length=200)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("peer", "Peer Node"),
                            ("orderer", "Orderer Node"),
                            ("ca", "Certificate Authority"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                ("host", models.CharField(max_length=200)),
                ("port", models.IntegerField()),
                ("endpoint_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_online", models.BooleanField(default=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "uptime_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("total_transactions_processed", models.BigIntegerField(default=0)),
                ("last_block_number", models.BigIntegerField(blank=True, null=True)),
                ("joined_network_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_nodes",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain Node",
                "verbose_name_plural": "Blockchain Nodes",
                "db_table": "blockchain_nodes",
            },
        ),
        migrations.AddField(
            model_name="batchcontribution",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blockchain.fpobatch"
            ),
        ),
        migrations.AddField(
            model_name="batchcontribution",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="farmers.farmplot",
            ),
        ),
        migrations.AddField(
            model_name="batchcontribution",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farmers.farmer"
            ),
        ),
        migrations.AddField(
            model_name="batchcontribution",
            name="procurement_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="procurement.procurementorder",
            ),
        ),
        migrations.CreateModel(
            name="TraceabilityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("sowing", "Sowing"),
                            ("growth", "Growth Phase"),
                            ("harvest", "Harvesting"),
                            ("collection", "Collection at FPO"),
                            ("quality_check", "Quality Check"),
                            ("grading", "Grading & Sorting"),
                            ("storage", "Storage"),
                            ("processing", "Processing"),
                            ("packaging", "Packaging"),
                            ("dispatch", "Dispatch"),
                            ("transit", "In Transit"),
                            ("delivery", "Delivery"),
                            ("retail", "Retail Sale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stage_name", models.CharField(max_length=200)),
                ("stage_description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("stage_timestamp", models.DateTimeField()),
                (
                    "duration_hours",
                    models.IntegerField(
                        blank=True, help_text="Duration spent at this stage", null=True
                    ),
                ),
                (
                    "responsible_organization",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("quality_observations", models.TextField(blank=True)),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "photos",
                    models.JSONField(default=list, help_text="List of photo URLs"),
                ),
                (
                    "documents",
                    models.JSONField(default=list, help_text="List of document URLs"),
                ),
                (
                    "record_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of this record",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        default=dict, help_text="Stage-specific additional data"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traceability_records",
                        to="blockchain.fpobatch",
                    ),
                ),
                (
                    "previous_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_records",
                        to="blockchain.traceabilityrecord",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Traceability Record",
                "verbose_name_plural": "Traceability Records",
                "db_table": "traceability_records",
                "ordering": ["stage_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["batch", "stage"], name="traceabilit_batch_i_758181_idx"
                    ),
                    models.Index(
                        fields=["stage_timestamp"],
                        name="traceabilit_stage_t_d584ac_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QRCodeScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("operating_system", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("scan_data", models.JSONField(default=dict)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="blockchain.qrcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Scan",
                "verbose_name_plural": "QR Code Scans",
                "db_table": "qr_code_scans",
                "ordering": ["-scan_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["scan_timestamp"], name="qr_code_sca_scan_ti_b128eb_idx"
                    ),
                    models.Index(
                        fields=["qr_code", "scan_timestamp"],
                        name="qr_code_sca_qr_code_5bb2e4_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["qr_code"], name="qr_codes_qr_code_51374e_idx"),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["qr_type"], name="qr_codes_qr_type_1dcb70_idx"),
        ),
        migrations.AddIndex(
            model_name="fpobatch",
            index=models.Index(
                fields=["batch_number"], name="fpo_batches_batch_n_d2d6e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpobatch",
            index=models.Index(
                fields=["blockchain_hash"], name="fpo_batches_blockch_5d3c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fpobatch",
            index=models.Index(fields=["status"], name="fpo_batches_status_cf8864_idx"),
        ),
        migrations.AddIndex(
            model_name="fpobatch",
            index=models.Index(
                fields=["harvest_start_date"], name="fpo_batches_harvest_190af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchaintransaction",
            index=models.Index(
                fields=["transaction_hash"], name="blockchain__transac_9bd57a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchaintransaction",
            index=models.Index(fields=["status"], name="blockchain__status_946598_idx"),
        ),
        migrations.AddIndex(
            model_name="blockchaintransaction",
            index=models.Index(
                fields=["timestamp"], name="blockchain__timesta_e2c367_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchcontribution",
            unique_together={("batch", "farmer", "procurement_order")},
        ),
    ]
