# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('action_type', models.CharField(choices=[('created', 'Lot Created'), ('procured', 'Procured by FPO'), ('quality_checked', 'Quality Checked'), ('shipped', 'Shipped'), ('received', 'Received by Processor'), ('processed', 'Processed'), ('packaged', 'Packaged')], max_length=50)),
                ('actor_id', models.UUIDField(help_text='UUID of the user who performed the action')),
                ('actor_role', models.CharField(help_text='Role of the actor (farmer/fpo/processor)', max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('data_hash', models.CharField(help_text='SHA-256 hash of transaction data', max_length=64)),
                ('previous_hash', models.CharField(blank=True, help_text='Hash of previous transaction (creates chain)', max_length=64)),
                ('transaction_data', models.JSONField(default=dict, help_text='Actual transaction details')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'db_table': 'blockchain_transactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_data', models.TextField(help_text='Data encoded in QR (typically URL)')),
                ('qr_version', models.IntegerField(default=1)),
                ('scan_count', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'db_table': 'qr_codes',
            },
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journey', models.JSONField(default=list, help_text='Complete journey from farm to consumer')),
                ('qr_code_data', models.TextField(blank=True, help_text='Data encoded in QR code')),
                ('certificate_url', models.URLField(blank=True, help_text='URL to downloadable certificate')),
                ('certificate_hash', models.CharField(blank=True, help_text='Hash of certificate for verification', max_length=64)),
                ('total_transactions', models.IntegerField(default=0)),
                ('chain_verified', models.BooleanField(default=True)),
                ('last_verification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Traceability Record',
                'verbose_name_plural': 'Traceability Records',
                'db_table': 'traceability_records',
            },
        ),
    ]
