# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceabilityrecord',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traceability', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='lots.procurementlot'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='lots.procurementlot'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['lot', 'created_at'], name='blockchain__lot_id_9acdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_id'], name='blockchain__transac_ff6f9f_idx'),
        ),
    ]
