# Generated by Django 4.2.27 on 2025-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaintransaction',
            name='action_type',
            field=models.CharField(choices=[('created', 'Lot Created'), ('procured', 'Procured by FPO'), ('quality_checked', 'Quality Checked'), ('warehouse_in', 'Warehouse Stock In'), ('warehouse_out', 'Warehouse Stock Out'), ('sale_agreed', 'Sale Agreement'), ('shipped', 'Shipped'), ('received', 'Received by Processor'), ('processed', 'Processing Completed'), ('stage_completed', 'Processing Stage Completed'), ('packaged', 'Product Packaged'), ('payment_completed', 'Payment Completed')], max_length=50),
        ),
    ]
