# Generated by Django 4.2.26 on 2025-11-26 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_type', models.CharField(choices=[('SELL', 'Sell Offer'), ('BUY', 'Buy Requirement')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In quintals', max_digits=10)),
                ('quality_grade', models.CharField(max_length=10)),
                ('moisture_content', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('oil_content', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('buyer_fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_listings', to='users.fpoprofile')),
                ('buyer_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_listings', to='users.processorprofile')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advisory.croptype')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.farmerprofile')),
                ('fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.fpoprofile')),
            ],
            options={
                'db_table': 'market_listings',
            },
        ),
        migrations.CreateModel(
            name='PriceForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('confidence_interval_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_interval_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.croptype')),
            ],
            options={
                'db_table': 'price_forecasts',
                'indexes': [models.Index(fields=['crop_type', 'forecast_date'], name='price_forec_crop_ty_51cdb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, help_text='In quintals', max_digits=10)),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='₹', max_digits=12)),
                ('delivery_address', models.TextField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('buyer_fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.fpoprofile')),
                ('buyer_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.processorprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.marketlisting')),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['order_id'], name='orders_order_i_88e57b_idx'), models.Index(fields=['status'], name='orders_status_762191_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('market_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, help_text='₹/quintal', max_digits=10)),
                ('source', models.CharField(default='AGMARKNET', max_length=100)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.croptype')),
            ],
            options={
                'db_table': 'market_prices',
                'indexes': [models.Index(fields=['crop_type', 'state', 'date'], name='market_pric_crop_ty_b4b8ff_idx')],
                'unique_together': {('crop_type', 'state', 'date', 'market_name')},
            },
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['listing_type', 'is_active'], name='market_list_listing_d2db85_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['crop_type', 'state'], name='market_list_crop_ty_2daefe_idx'),
        ),
    ]
