# Generated by Django 4.2.26 on 2025-11-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmers", "__first__"),
        ("fpos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriStackIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agri_stack_farmer_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("land_records_synced", models.BooleanField(default=False)),
                ("land_records_last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "total_land_area_from_agristack",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("digilocker_linked", models.BooleanField(default=False)),
                (
                    "digilocker_documents",
                    models.JSONField(
                        default=list,
                        help_text="List of documents fetched from DigiLocker",
                    ),
                ),
                ("aadhaar_verified", models.BooleanField(default=False)),
                (
                    "aadhaar_verification_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "aadhaar_last_four_digits",
                    models.CharField(blank=True, max_length=4),
                ),
                ("bank_account_verified", models.BooleanField(default=False)),
                ("bank_verification_date", models.DateTimeField(blank=True, null=True)),
                ("pmfby_enrolled", models.BooleanField(default=False)),
                ("pmfby_policy_number", models.CharField(blank=True, max_length=50)),
                ("pmfby_data", models.JSONField(blank=True, default=dict)),
                ("has_kisan_credit_card", models.BooleanField(default=False)),
                ("kcc_number", models.CharField(blank=True, max_length=50)),
                (
                    "kcc_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("kcc_data", models.JSONField(blank=True, default=dict)),
                (
                    "soil_health_card_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("soil_health_data", models.JSONField(blank=True, default=dict)),
                ("soil_health_last_updated", models.DateField(blank=True, null=True)),
                ("pm_kisan_beneficiary", models.BooleanField(default=False)),
                (
                    "pm_kisan_registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("failed", "Verification Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_full_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agri-Stack Integration",
                "verbose_name_plural": "Agri-Stack Integrations",
                "db_table": "agri_stack_integrations",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_name", models.CharField(max_length=200)),
                (
                    "api_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("api_secret", models.CharField(max_length=64)),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("full_access", "Full Access"),
                            ("read_only", "Read Only"),
                            ("write_only", "Write Only"),
                            ("limited", "Limited Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "allowed_endpoints",
                    models.JSONField(
                        default=list, help_text="List of allowed API endpoints"
                    ),
                ),
                (
                    "allowed_ip_addresses",
                    models.JSONField(
                        default=list, help_text="Whitelist of IP addresses"
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=100)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("can_rotate", models.BooleanField(default=True)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("rotation_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("service_name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("agri_stack", "Agri-Stack"),
                            ("weather", "Weather API"),
                            ("satellite", "Satellite Data"),
                            ("payment_gateway", "Payment Gateway"),
                            ("sms_gateway", "SMS Gateway"),
                            ("email_service", "Email Service"),
                            ("government_scheme", "Government Scheme API"),
                            ("ename", "eNAM Portal"),
                            ("digilocker", "DigiLocker"),
                            ("upi", "UPI Payment"),
                            ("nabard", "NABARD FPO Database"),
                            ("sfac", "SFAC Portal"),
                            ("fci", "FCI Portal"),
                            ("pmfby", "PMFBY (Crop Insurance)"),
                            ("kcc", "Kisan Credit Card"),
                            ("bhuvan", "ISRO Bhuvan"),
                            ("imd", "India Meteorological Department"),
                            ("whatsapp", "WhatsApp Business API"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "service_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("provider_name", models.CharField(max_length=200)),
                ("provider_website", models.URLField(blank=True)),
                ("base_url", models.URLField(help_text="Base API URL")),
                ("api_version", models.CharField(default="v1", max_length=20)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("api_key", "API Key"),
                            ("oauth2", "OAuth 2.0"),
                            ("basic", "Basic Auth"),
                            ("bearer", "Bearer Token"),
                            ("jwt", "JWT"),
                            ("none", "No Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "custom_headers",
                    models.JSONField(
                        default=dict, help_text="Custom headers to send with requests"
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(
                        default=60, help_text="Max requests per minute"
                    ),
                ),
                (
                    "rate_limit_per_day",
                    models.IntegerField(
                        default=10000, help_text="Max requests per day"
                    ),
                ),
                (
                    "connection_timeout",
                    models.IntegerField(default=10, help_text="Timeout in seconds"),
                ),
                (
                    "read_timeout",
                    models.IntegerField(default=30, help_text="Timeout in seconds"),
                ),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_delay_seconds", models.IntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("health_check_url", models.URLField(blank=True)),
                ("is_healthy", models.BooleanField(default=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("average_response_time_ms", models.IntegerField(default=0)),
                (
                    "cost_per_request",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Cost in INR",
                        max_digits=8,
                    ),
                ),
                (
                    "monthly_subscription_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost_incurred",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("documentation_url", models.URLField(blank=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=15)),
                ("webhook_enabled", models.BooleanField(default=False)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=200)),
                (
                    "technical_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "technical_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "technical_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("auto_renewal", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External Service",
                "verbose_name_plural": "External Services",
                "db_table": "external_services",
            },
        ),
        migrations.CreateModel(
            name="WeatherAPICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_name", models.CharField(max_length=200)),
                (
                    "weather_data",
                    models.JSONField(default=dict, help_text="Current weather data"),
                ),
                (
                    "forecast_data",
                    models.JSONField(default=list, help_text="7-day forecast"),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("imd", "India Meteorological Department"),
                            ("openweather", "OpenWeatherMap"),
                            ("weatherapi", "WeatherAPI.com"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cached_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_valid", models.BooleanField(default=True)),
                ("access_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weather API Cache",
                "verbose_name_plural": "Weather API Cache",
                "db_table": "weather_api_cache",
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="weather_api_latitud_c35af4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="weather_api_expires_8045ac_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SatelliteDataFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "area_polygon",
                    models.JSONField(
                        default=dict, help_text="GeoJSON polygon for area"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("ndvi", "NDVI (Vegetation Index)"),
                            ("soil_moisture", "Soil Moisture"),
                            ("land_cover", "Land Cover"),
                            ("crop_health", "Crop Health"),
                            ("rainfall", "Rainfall Estimate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "satellite_source",
                    models.CharField(
                        choices=[
                            ("bhuvan", "ISRO Bhuvan"),
                            ("sentinel", "Sentinel"),
                            ("landsat", "Landsat"),
                            ("modis", "MODIS"),
                        ],
                        max_length=50,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("data_url", models.URLField(blank=True)),
                (
                    "data_file",
                    models.FileField(
                        blank=True, null=True, upload_to="satellite_data/"
                    ),
                ),
                ("processed_data", models.JSONField(default=dict)),
                ("analysis_results", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("fetching", "Fetching"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellite_data",
                        to="farmers.farmplot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Satellite Data Fetch",
                "verbose_name_plural": "Satellite Data Fetches",
                "db_table": "satellite_data_fetches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("payout", "Payout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("razorpay", "Razorpay"),
                            ("paytm", "Paytm"),
                            ("phonepe", "PhonePe"),
                            ("upi", "UPI"),
                            ("neft", "NEFT"),
                            ("rtgs", "RTGS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "gateway_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "gst_on_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "internal_transaction_id",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("gateway_order_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_received", models.BooleanField(default=False)),
                ("webhook_data", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.order",
                    ),
                ),
                (
                    "related_procurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.procurementorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Gateway Transaction",
                "verbose_name_plural": "Payment Gateway Transactions",
                "db_table": "payment_gateway_transactions",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("request_url", models.TextField()),
                ("request_headers", models.JSONField(default=dict)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("rate_limited", "Rate Limited"),
                            ("unauthorized", "Unauthorized"),
                            ("not_found", "Not Found"),
                            ("server_error", "Server Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("stack_trace", models.TextField(blank=True)),
                ("is_retry", models.BooleanField(default=False)),
                ("retry_attempt", models.IntegerField(default=0)),
                ("original_request_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_module",
                    models.CharField(
                        help_text="Module that triggered this API call", max_length=50
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=50)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "request_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "external_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.externalservice",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Log",
                "verbose_name_plural": "Integration Logs",
                "db_table": "integration_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="externalservice",
            index=models.Index(
                fields=["service_type"], name="external_se_service_ef519f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalservice",
            index=models.Index(fields=["status"], name="external_se_status_1375ee_idx"),
        ),
        migrations.AddField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="fpos.fpo",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agristackintegration",
            name="farmer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agri_stack_data",
                to="farmers.farmer",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewaytransaction",
            index=models.Index(
                fields=["internal_transaction_id"],
                name="payment_gat_interna_92006a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewaytransaction",
            index=models.Index(
                fields=["gateway_transaction_id"], name="payment_gat_gateway_608de7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewaytransaction",
            index=models.Index(fields=["status"], name="payment_gat_status_c293c6_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["external_service", "status"],
                name="integration_externa_049c27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["created_at"], name="integration_created_b8d84c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(fields=["status"], name="integration_status_79d2d0_idx"),
        ),
    ]
