
export const OILSEED_CROPS = [
  {
    id: 'groundnut' as const,
    name: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    averageYieldPerAcre: '20-25 quintals',
    growthPeriod: '90-150 days',
    oilContentRange: '45-50%',
    varieties: [
      'TMV-2',
      'GG-2',
      'TAG-24',
      'Kadiri-3',
      'ICGV-91114',
      'Other',
    ],
  },
  {
    id: 'mustard' as const,
    name: 'Mustard',
    scientificName: 'Brassica juncea',
    averageYieldPerAcre: '8-12 quintals',
    growthPeriod: '90-120 days',
    oilContentRange: '37-42%',
    varieties: [
      'Pusa Bold',
      'Varuna',
      'RH-30',
      'Kranti',
      'Pusa Mustard-25',
      'Other',
    ],
  },
  {
    id: 'sunflower' as const,
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    averageYieldPerAcre: '8-12 quintals',
    growthPeriod: '85-100 days',
    oilContentRange: '38-42%',
    varieties: [
      'KBSH-1',
      'Morden',
      'BSH-1',
      'PSH-569',
      'Co-4',
      'Other',
    ],
  },
  {
    id: 'soybean' as const,
    name: 'Soybean',
    scientificName: 'Glycine max',
    averageYieldPerAcre: '10-15 quintals',
    growthPeriod: '90-120 days',
    oilContentRange: '18-22%',
    varieties: [
      'JS-335',
      'JS-93-05',
      'MAUS-71',
      'PS-1092',
      'NRC-37',
      'Other',
    ],
  },
  {
    id: 'sesame' as const,
    name: 'Sesame',
    scientificName: 'Sesamum indicum',
    averageYieldPerAcre: '2-4 quintals',
    growthPeriod: '80-90 days',
    oilContentRange: '48-52%',
    varieties: [
      'TMV-3',
      'TMV-4',
      'Rama',
      'Gujarat Til-2',
      'RT-54',
      'Other',
    ],
  },
  {
    id: 'safflower' as const,
    name: 'Safflower',
    scientificName: 'Carthamus tinctorius',
    averageYieldPerAcre: '6-8 quintals',
    growthPeriod: '120-150 days',
    oilContentRange: '32-38%',
    varieties: [
      'JSF-1',
      'PBNS-12',
      'Sharda',
      'NARI-6',
      'A-1',
      'Other',
    ],
  },
  {
    id: 'castor' as const,
    name: 'Castor',
    scientificName: 'Ricinus communis',
    averageYieldPerAcre: '10-15 quintals',
    growthPeriod: '150-180 days',
    oilContentRange: '46-52%',
    varieties: [
      'GCH-7',
      'DCS-9',
      'DCH-177',
      'Kranthi',
      '48-1',
      'Other',
    ],
  },
  {
    id: 'linseed' as const,
    name: 'Linseed',
    scientificName: 'Linum usitatissimum',
    averageYieldPerAcre: '4-6 quintals',
    growthPeriod: '110-140 days',
    oilContentRange: '35-42%',
    varieties: [
      'T-397',
      'LC-2023',
      'Shubhra',
      'Shekhar',
      'Neelum',
      'Other',
    ],
  },
  {
    id: 'niger' as const,
    name: 'Niger',
    scientificName: 'Guizotia abyssinica',
    averageYieldPerAcre: '2-3 quintals',
    growthPeriod: '90-110 days',
    oilContentRange: '37-42%',
    varieties: [
      'IGP-76',
      'GA-10',
      'Ootacamund',
      'Deomali',
      'RNS-12',
      'Other',
    ],
  },
] as const;


export const CROP_STATUS_CONFIG = {
  planted: {
    label: 'Planted',
    color: '#10B981',
    bgColor: '#D1FAE5',
    icon: 'leaf-outline',
  },
  growing: {
    label: 'Growing',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
    icon: 'trending-up-outline',
  },
  flowering: {
    label: 'Flowering',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    icon: 'flower-outline',
  },
  matured: {
    label: 'Matured',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    icon: 'checkmark-circle-outline',
  },
  harvested: {
    label: 'Harvested',
    color: '#059669',
    bgColor: '#D1FAE5',
    icon: 'archive-outline',
  },
  processed: {
    label: 'Processed',
    color: '#6366F1',
    bgColor: '#E0E7FF',
    icon: 'cube-outline',
  },
  sold: {
    label: 'Sold',
    color: '#EC4899',
    bgColor: '#FCE7F3',
    icon: 'cash-outline',
  },
} as const;

export const INPUT_TYPES = [
  { value: 'fertilizer', label: 'Fertilizer', icon: 'flask-outline' },
  { value: 'pesticide', label: 'Pesticide', icon: 'bug-outline' },
  { value: 'herbicide', label: 'Herbicide', icon: 'leaf-outline' },
  { value: 'seed', label: 'Seed', icon: 'water-outline' },
  { value: 'irrigation', label: 'Irrigation', icon: 'water-outline' },
] as const;

export const QUALITY_GRADES = [
  { value: 'A', label: 'Grade A (Premium)', minOil: 48, color: '#10B981' },
  { value: 'B', label: 'Grade B (Good)', minOil: 45, color: '#3B82F6' },
  { value: 'C', label: 'Grade C (Average)', minOil: 42, color: '#F59E0B' },
  { value: 'D', label: 'Grade D (Below Average)', minOil: 38, color: '#EF4444' },
] as const;

export const STORAGE_METHODS = [
  { value: 'warehouse', label: 'Warehouse' },
  { value: 'farm', label: 'On Farm' },
  { value: 'cold_storage', label: 'Cold Storage' },
  { value: 'fpo_facility', label: 'FPO Facility' },
] as const;

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Gujarat',
  'Karnataka',
  'Madhya Pradesh',
  'Maharashtra',
  'Rajasthan',
  'Tamil Nadu',
  'Telangana',
  'Uttar Pradesh',
  'West Bengal',
] as const;