# Generated by Django 4.2.26 on 2025-11-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("fpos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("lot_number", models.CharField(max_length=50)),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial stored quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Current quantity", max_digits=12
                    ),
                ),
                (
                    "withdrawn_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "loss_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("quality_grade", models.CharField(max_length=10)),
                (
                    "moisture_content_at_entry",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("storage_chamber", models.CharField(max_length=50)),
                ("stack_number", models.CharField(blank=True, max_length=50)),
                ("storage_start_date", models.DateField()),
                ("expected_withdrawal_date", models.DateField(blank=True, null=True)),
                ("actual_withdrawal_date", models.DateField(blank=True, null=True)),
                ("storage_duration_days", models.IntegerField(default=0)),
                (
                    "storage_charges_per_month",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "total_storage_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "handling_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("partially_withdrawn", "Partially Withdrawn"),
                            ("fully_withdrawn", "Fully Withdrawn"),
                            ("damaged", "Damaged"),
                        ],
                        default="stored",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_inventory",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_inventory",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventory",
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("warehouse_name", models.CharField(max_length=200)),
                (
                    "warehouse_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("fpo_owned", "FPO Owned"),
                            ("fci", "Food Corporation of India"),
                            ("cwc", "Central Warehousing Corporation"),
                            ("swc", "State Warehousing Corporation"),
                            ("private", "Private"),
                            ("cooperative", "Cooperative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("covered", "Covered Warehouse"),
                            ("cold_storage", "Cold Storage"),
                            ("silo", "Silo"),
                            ("open_yard", "Open Yard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owner_name", models.CharField(max_length=200)),
                ("owner_contact", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("village", models.CharField(blank=True, max_length=100)),
                ("block", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("location", models.JSONField(blank=True, null=True)),
                (
                    "total_capacity_quintals",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "covered_capacity_quintals",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "open_capacity_quintals",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "occupied_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_capacity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "utilization_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("number_of_chambers", models.IntegerField(default=1)),
                ("has_weighbridge", models.BooleanField(default=False)),
                ("has_fumigation_facility", models.BooleanField(default=False)),
                ("has_loading_dock", models.BooleanField(default=False)),
                ("has_security", models.BooleanField(default=True)),
                ("temperature_controlled", models.BooleanField(default=False)),
                ("humidity_controlled", models.BooleanField(default=False)),
                ("ventilation_system", models.BooleanField(default=True)),
                ("iot_enabled", models.BooleanField(default=False)),
                ("temperature_sensors", models.IntegerField(default=0)),
                ("humidity_sensors", models.IntegerField(default=0)),
                ("fssai_license", models.CharField(blank=True, max_length=14)),
                (
                    "wdra_registration",
                    models.CharField(
                        blank=True, help_text="WDRA registration number", max_length=50
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "storage_rate_per_quintal_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Storage charges in INR",
                        max_digits=8,
                    ),
                ),
                (
                    "loading_rate_per_quintal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "unloading_rate_per_quintal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("manager_name", models.CharField(max_length=200)),
                ("manager_contact", models.CharField(max_length=10)),
                ("manager_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("is_certified", models.BooleanField(default=False)),
                (
                    "total_storage_handled",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total quantity handled (quintals)",
                        max_digits=15,
                    ),
                ),
                ("average_storage_duration_days", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "warehouses",
            },
        ),
        migrations.CreateModel(
            name="StorageBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_number", models.CharField(max_length=50, unique=True)),
                (
                    "quantity_to_store",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("expected_storage_duration_months", models.IntegerField()),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("expected_arrival_date", models.DateField()),
                ("actual_arrival_date", models.DateField(blank=True, null=True)),
                ("expected_withdrawal_date", models.DateField()),
                (
                    "estimated_storage_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "advance_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crops.cropmaster",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_bookings",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_bookings",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "inventory",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="warehouses.inventory",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Booking",
                "verbose_name_plural": "Storage Bookings",
                "db_table": "storage_bookings",
            },
        ),
        migrations.CreateModel(
            name="QualityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Relative humidity %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "moisture_content",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("visual_inspection_done", models.BooleanField(default=False)),
                ("pest_infestation_detected", models.BooleanField(default=False)),
                ("fungal_growth_detected", models.BooleanField(default=False)),
                ("rodent_activity_detected", models.BooleanField(default=False)),
                ("observations", models.TextField(blank=True)),
                ("fumigation_done", models.BooleanField(default=False)),
                ("aeration_done", models.BooleanField(default=False)),
                ("other_actions", models.TextField(blank=True)),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True, help_text="Quality score 0-100", null=True
                    ),
                ),
                ("iot_device_id", models.CharField(blank=True, max_length=50)),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_logs",
                        to="warehouses.inventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Log",
                "verbose_name_plural": "Quality Logs",
                "db_table": "quality_logs",
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="LossRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loss_date", models.DateField()),
                (
                    "loss_type",
                    models.CharField(
                        choices=[
                            ("natural_drying", "Natural Drying Loss"),
                            ("pest", "Pest Damage"),
                            ("rodent", "Rodent Damage"),
                            ("fungal", "Fungal Infection"),
                            ("moisture", "Moisture Damage"),
                            ("spillage", "Spillage"),
                            ("fire", "Fire"),
                            ("flood", "Flood"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "loss_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Loss quantity in quintals",
                        max_digits=12,
                    ),
                ),
                (
                    "loss_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "market_value_per_quintal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_financial_loss",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("root_cause", models.TextField()),
                ("contributing_factors", models.JSONField(default=list)),
                ("could_have_been_prevented", models.BooleanField(default=False)),
                ("preventive_measures", models.TextField(blank=True)),
                ("insurance_claimed", models.BooleanField(default=False)),
                (
                    "claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("not_filed", "Not Filed"),
                            ("filed", "Filed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("settled", "Settled"),
                        ],
                        default="not_filed",
                        max_length=20,
                    ),
                ),
                (
                    "loss_report",
                    models.FileField(blank=True, null=True, upload_to="loss_reports/"),
                ),
                ("photos", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_records",
                        to="warehouses.inventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loss Record",
                "verbose_name_plural": "Loss Records",
                "db_table": "loss_records",
                "ordering": ["-loss_date"],
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="warehouses.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="FPOStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "average_quantity_stored",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "peak_quantity_stored",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("storage_days", models.IntegerField()),
                (
                    "storage_charges",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "handling_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maintenance_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "insurance_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fpo_share", models.DecimalField(decimal_places=2, max_digits=12)),
                ("member_share", models.DecimalField(decimal_places=2, max_digits=12)),
                ("members_using_storage", models.IntegerField()),
                (
                    "per_member_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fpo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Storage",
                "verbose_name_plural": "FPO Storage",
                "db_table": "fpo_storage",
            },
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["warehouse_code"], name="warehouses_warehou_fd3850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["district", "state"], name="warehouses_distric_98d498_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active"], name="warehouses_is_acti_178fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["batch_number"], name="inventory_batch_n_eae8fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["status"], name="inventory_status_2fc879_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fpostorage",
            unique_together={("fpo", "warehouse", "month", "year")},
        ),
    ]
