# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpos', '0001_initial'),
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('karnataka', 'Karnataka'), ('uttar_pradesh', 'Uttar Pradesh'), ('haryana', 'Haryana'), ('punjab', 'Punjab'), ('tamil_nadu', 'Tamil Nadu'), ('west_bengal', 'West Bengal'), ('odisha', 'Odisha'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand'), ('bihar', 'Bihar')], max_length=50)),
                ('capacity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fpo_warehouses', to='fpos.fpoprofile')),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='lots.procurementlot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oil_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pass_status', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='lots.procurementlot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'quality_checks',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='lots.procurementlot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
