# Generated by Django 4.2.7 on 2025-12-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-movement_date']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for stock movement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='state',
            field=models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli_daman_diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50),
        ),
    ]
