# Generated by Django 4.2.7 on 2025-12-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpos', '0002_alter_fpoprofile_state_alter_fpowarehouse_state'),
        ('warehouses', '0002_alter_stockmovement_options_stockmovement_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='fpos.fpowarehouse'),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='fpos.fpowarehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='fpos.fpowarehouse'),
        ),
    ]
