# Generated by Django 4.2.27 on 2025-12-07 19:44

import apps.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('payer_id', models.UUIDField(help_text='UUID of payer')),
                ('payer_name', models.CharField(max_length=200)),
                ('payer_type', models.CharField(max_length=20)),
                ('payee_id', models.UUIDField(help_text='UUID of farmer')),
                ('payee_name', models.CharField(max_length=200)),
                ('payee_account_number', models.CharField(blank=True, max_length=20)),
                ('payee_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[apps.core.validators.validate_positive])),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Platform/FPO commission', max_digits=15)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Amount payable to farmer', max_digits=15)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('razorpay', 'Razorpay'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_processing', 'Payment Processing'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, max_length=200)),
                ('external_transaction_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount locked in pending transactions', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
    ]
