# Generated by Django 4.2.27 on 2025-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_charge_id_payment_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('razorpay', 'Razorpay'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=50),
        ),
    ]
