# Generated by Django 4.2.27 on 2025-12-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_initial'),
        ('bids', '0004_initial'),
        ('payments', '0004_remove_payment_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bids.bid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lots.procurementlot'),
        ),
    ]
