# Generated by Django 4.2.23 on 2025-12-04 19:19

import apps.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bidder_type', models.CharField(choices=[('fpo', 'FPO'), ('processor', 'Processor'), ('retailer', 'Retailer')], max_length=20)),
                ('bidder_id', models.UUIDField(help_text='UUID of FPO/Processor profile')),
                ('bidder_name', models.CharField(max_length=200)),
                ('offered_price_per_quintal', models.DecimalField(decimal_places=2, help_text='Offered price in ₹ per quintal', max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('quantity_quintals', models.DecimalField(decimal_places=2, help_text='Quantity willing to procure (can be partial)', max_digits=10, validators=[apps.core.validators.validate_positive])),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Total bid amount', max_digits=15)),
                ('pickup_location', models.CharField(blank=True, help_text='Where the bidder will collect from', max_length=200)),
                ('expected_pickup_date', models.DateField()),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days')], default='7_days', max_length=20)),
                ('advance_payment_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of advance payment offered', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message to the farmer')),
                ('farmer_response', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table': 'bids',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BidAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_scheduled_date', models.DateField()),
                ('actual_pickup_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('driver_phone', models.CharField(blank=True, max_length=15)),
                ('pickup_completed', models.BooleanField(default=False)),
                ('delivery_completed', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('actual_quantity_received_quintals', models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity received at pickup', max_digits=10, null=True)),
                ('quality_grade_verified', models.CharField(blank=True, max_length=3)),
                ('quality_check_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='bids.bid')),
            ],
            options={
                'verbose_name': 'Bid Acceptance',
                'verbose_name_plural': 'Bid Acceptances',
                'db_table': 'bid_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
