# Generated by Django 4.2.23 on 2025-12-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidacceptance',
            name='logistics_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_deliveries', to='logistics.logisticspartner'),
        ),
        migrations.AddField(
            model_name='bidacceptance',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_acceptance', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lots.procurementlot'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['lot', 'status'], name='bids_lot_id_960dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder_user', 'status'], name='bids_bidder__1f5495_idx'),
        ),
    ]
