# Generated by Django 4.2.27 on 2025-12-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids_placed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lots.procurementlot'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['lot', 'status'], name='bids_lot_id_960dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bidder_user', 'status'], name='bids_bidder__1f5495_idx'),
        ),
    ]
