# Generated by Django 4.2.26 on 2025-11-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fpos", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmers", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("law", "New Law/Act"),
                            ("amendment", "Amendment"),
                            ("rule", "New Rule"),
                            ("notification", "Government Notification"),
                            ("circular", "Circular"),
                            ("guideline", "Guideline"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("issuing_authority", models.CharField(max_length=200)),
                ("notification_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("effective_date", models.DateField()),
                ("compliance_deadline", models.DateField(blank=True, null=True)),
                (
                    "impact_level",
                    models.CharField(
                        choices=[
                            ("high", "High Impact"),
                            ("medium", "Medium Impact"),
                            ("low", "Low Impact"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "affected_areas",
                    models.JSONField(
                        default=list, help_text="List of affected compliance areas"
                    ),
                ),
                ("action_required", models.TextField()),
                (
                    "official_document",
                    models.FileField(
                        blank=True, null=True, upload_to="regulatory_updates/"
                    ),
                ),
                (
                    "summary_document",
                    models.FileField(
                        blank=True, null=True, upload_to="regulatory_updates/summaries/"
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Regulatory Update",
                "verbose_name_plural": "Regulatory Updates",
                "db_table": "regulatory_updates",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="FPOCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moa_filed",
                    models.BooleanField(default=False, verbose_name="MOA Filed"),
                ),
                (
                    "aoa_filed",
                    models.BooleanField(default=False, verbose_name="AOA Filed"),
                ),
                ("pan_obtained", models.BooleanField(default=False)),
                ("tan_obtained", models.BooleanField(default=False)),
                ("gst_registered", models.BooleanField(default=False)),
                ("last_agm_date", models.DateField(blank=True, null=True)),
                ("next_agm_due_date", models.DateField(blank=True, null=True)),
                ("agm_compliant", models.BooleanField(default=True)),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                ("next_audit_due_date", models.DateField(blank=True, null=True)),
                ("audit_compliant", models.BooleanField(default=True)),
                ("auditor_name", models.CharField(blank=True, max_length=200)),
                ("annual_return_filed", models.BooleanField(default=False)),
                ("last_annual_return_fy", models.CharField(blank=True, max_length=10)),
                ("minimum_board_meetings_per_year", models.IntegerField(default=4)),
                ("board_meetings_held_this_year", models.IntegerField(default=0)),
                ("board_meeting_compliant", models.BooleanField(default=True)),
                ("books_of_accounts_maintained", models.BooleanField(default=True)),
                ("tax_returns_filed", models.BooleanField(default=False)),
                ("gst_returns_filed", models.BooleanField(default=False)),
                ("tds_returns_filed", models.BooleanField(default=False)),
                ("fssai_license_valid", models.BooleanField(default=False)),
                ("fssai_expiry_date", models.DateField(blank=True, null=True)),
                ("wdra_registration_valid", models.BooleanField(default=False)),
                ("wdra_expiry_date", models.DateField(blank=True, null=True)),
                ("pf_registration_done", models.BooleanField(default=False)),
                ("esic_registration_done", models.BooleanField(default=False)),
                ("labor_laws_compliant", models.BooleanField(default=True)),
                (
                    "compliance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overall compliance score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "compliance_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Excellent (90-100)"),
                            ("B", "Good (75-89)"),
                            ("C", "Average (60-74)"),
                            ("D", "Poor (<60)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pending_compliances",
                    models.JSONField(
                        default=list, help_text="List of pending compliance items"
                    ),
                ),
                (
                    "compliance_alerts",
                    models.JSONField(
                        default=list, help_text="List of upcoming deadlines and alerts"
                    ),
                ),
                ("last_assessment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fpo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_dashboard",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "last_assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FPO Compliance",
                "verbose_name_plural": "FPO Compliance",
                "db_table": "fpo_compliance",
            },
        ),
        migrations.CreateModel(
            name="ComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("legal", "Legal Compliance"),
                            ("tax", "Tax Compliance"),
                            ("labor", "Labor Law Compliance"),
                            ("environmental", "Environmental Compliance"),
                            ("quality", "Quality Standards"),
                            ("food_safety", "Food Safety"),
                            ("data_privacy", "Data Privacy"),
                            ("financial", "Financial Reporting"),
                        ],
                        max_length=30,
                    ),
                ),
                ("compliance_area", models.CharField(max_length=200)),
                ("requirement", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("under_review", "Under Review"),
                            ("action_required", "Action Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("findings", models.TextField()),
                ("gaps_identified", models.JSONField(default=list)),
                ("corrective_actions", models.TextField(blank=True)),
                ("action_deadline", models.DateField(blank=True, null=True)),
                ("action_completed", models.BooleanField(default=False)),
                ("action_completed_date", models.DateField(blank=True, null=True)),
                (
                    "assessment_report",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance/assessments/"
                    ),
                ),
                (
                    "evidence_documents",
                    models.JSONField(
                        default=list, help_text="List of evidence document URLs"
                    ),
                ),
                ("next_review_date", models.DateField()),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_records",
                        to="fpos.fpo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Record",
                "verbose_name_plural": "Compliance Records",
                "db_table": "compliance_records",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("fssai", "FSSAI License"),
                            ("agmark", "Agmark Certification"),
                            ("organic", "Organic Certification"),
                            ("fair_trade", "Fair Trade Certification"),
                            ("gmp", "GMP Certification"),
                            ("haccp", "HACCP Certification"),
                            ("iso", "ISO Certification"),
                            ("brc", "BRC Certification"),
                            ("halal", "Halal Certification"),
                            ("kosher", "Kosher Certification"),
                            ("rainforest", "Rainforest Alliance"),
                            ("global_gap", "GlobalGAP"),
                            ("wdra", "WDRA Registration"),
                            ("apeda", "APEDA Registration"),
                            ("spice_board", "Spice Board Certification"),
                            ("tea_board", "Tea Board Certification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("certificate_name", models.CharField(max_length=200)),
                ("issuing_authority", models.CharField(max_length=200)),
                ("issuing_office", models.CharField(blank=True, max_length=200)),
                ("inspector_name", models.CharField(blank=True, max_length=200)),
                ("application_date", models.DateField()),
                ("inspection_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("inspection_scheduled", "Inspection Scheduled"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "application_form",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/applications/"
                    ),
                ),
                (
                    "certificate_document",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/documents/"
                    ),
                ),
                (
                    "inspection_report",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/inspections/"
                    ),
                ),
                (
                    "scope_of_certification",
                    models.TextField(help_text="Products/processes covered"),
                ),
                (
                    "certified_products",
                    models.JSONField(
                        default=list, help_text="List of certified products"
                    ),
                ),
                (
                    "compliance_requirements",
                    models.JSONField(
                        default=list, help_text="List of compliance requirements"
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "annual_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "inspection_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fee_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_renewable", models.BooleanField(default=True)),
                ("renewal_reminder_sent", models.BooleanField(default=False)),
                ("days_before_expiry_to_remind", models.IntegerField(default=60)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_url",
                    models.URLField(
                        blank=True, help_text="URL to verify certificate online"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="farmers.farmer",
                    ),
                ),
                (
                    "fpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="fpos.fpo",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "db_table": "certificates",
                "ordering": ["-issue_date"],
                "indexes": [
                    models.Index(
                        fields=["certificate_number"],
                        name="certificate_certifi_1d3ba1_idx",
                    ),
                    models.Index(
                        fields=["status"], name="certificate_status_a01db5_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="certificate_expiry__23591c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("payment", "Payment"),
                            ("export", "Export Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_description", models.TextField()),
                ("user_role", models.CharField(max_length=50)),
                (
                    "object_type",
                    models.CharField(help_text="Model name", max_length=100),
                ),
                ("object_id", models.CharField(max_length=100)),
                ("object_representation", models.CharField(max_length=500)),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Previous values before change",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="New values after change"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.CharField(max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_logs_user_id_88267f_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_logs_object__457405_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="audit_logs_action__168beb_idx"
                    ),
                ],
            },
        ),
    ]
